### ISSUE TITLE
Report Button

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#10]
Maybe there should be a report button next to each of the DNS Queries, like the Wiki and google button, so users can report ip's they think is suspicious, and if enough people report it, it can get blocked or someone can review them. just an idea.

**Comment by quidsup** [comment]
Yes I like that idea

**Comment by quidsup** [comment]
I've added a reporting page to my site http://quidsup.net/notrack/report.php?site=somesite.com
Now all it needs is a reporting button added to the stats page

**Comment by quidsup** [comment]
Report button added now in v0.5.1
