### ISSUE TITLE
Incorrect IP's

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#101]
It seems all ip's under dns leases are incorrect except ones i define in the dnsmasq.conf because my tablet and wii are 192.168.1.4 and 1.3 respectivly http://prntscr.com/c97l7n it may have something to do with the NAS (NoTrack) being on the modem and everything else plugged into the router... but it recognizes them... just not with the right ip, maybe i'm wrong though.

**Comment by fernfrost** [comment]
I don't have this problem.
Not quite sure what you mean with notrack being on the modem? Not plugged into the router?
Have you disabled dhcp in your router?
In my router admin i pointed the dns server to the ip of notrack and that works fine.

**Comment by ShayBox** [comment]
It works, but in the dns leases page, the ip's are wrong. 
and i have a modem, and a router. the server running notrack is plugged into the modem, then i point the modem and router to 192.168.0.100 (static) and it works... the ip's are just showing up incorrectly

**Comment by fernfrost** [comment]
Possible to try connecting it to the router and see if that makes a difference?

Not sure how you would purge the leases in notrack so that it would update though...
