### ISSUE TITLE
Stacking logs? 

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#102]
This and edatasales.com (less than this) http://prntscr.com/c9ch4s are spamming the blocked of the week  list, maybe a way to have a time-range if there are 2 of the same things being blocked next to eachother to clear it, and have a x32 or however many times it shows.

**Comment by quidsup** [comment]
Start with this simple version and let me know what you think.
I've reversed the list, so latest blocked sites are on top.

**Comment by ShayBox** [comment]
Thats a good idea, but is this what its supposed to look like? http://prntscr.com/c9esst

**Comment by quidsup** [comment]
Yes for Chrome
Looked better in Firefox
I've got an alternative solution to improve the look...
