### ISSUE TITLE
Domains blocked not updated on dashboard

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#104]
Latest dev version, shows 0 domains eventough there are
![image](https://cloud.githubusercontent.com/assets/10121067/17930782/c56d6c64-69ff-11e6-9b01-5991151c5094.png)

**Comment by fernfrost** [comment]
Did you update or make a fresh install?

I have done both and havnt been able to reproduce the problem?

What happens if you try to update the blocklist?

**Comment by duramato** [comment]
Update.
Updating the blocklists shows the same behaviour, after they are update it shows `0 Domains`

**Comment by fernfrost** [comment]
Does it show "Processing" first?

**Comment by duramato** [comment]
Yes

**Comment by quidsup** [comment]
As of v0.7.15 I changed it to do display the output of `notrack --count`
Have you got an older version of notrack script?
Run upgrade from web gui.

**Comment by duramato** [comment]
```
~# notrack --count
92416
```
I'm on the latest git version

**Comment by quidsup** [comment]
Does it display the same when launched without sudo/root privileges?

**Comment by duramato** [comment]
```
~# sudo -u www-data notrack --count
92416
```
But the default user is root

**Comment by quidsup** [comment]
I had an idea that your distro might need the full path included

**Comment by duramato** [comment]
seems it's working now 
![image](https://cloud.githubusercontent.com/assets/10121067/18057664/d44640fa-6e08-11e6-8f82-3b4b820eafbe.png)
