### ISSUE TITLE
Option to add blocker lists

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#11]
Maybe an option to add your own blocker lists, like EasyList or EasyPrivicy, so it can be an adblocker aswell, becasue you cant have pi-hole and notrack installed at the same time, on the same machine atleast. that would be cool.

P.S. I dont know if you included this list in your already blocked list, but heres a big list of common known https://easylist.adblockplus.org/en/ theres multple lists, but i think you probbably got them

**Comment by ShayBox** [comment]
Also made a install video https://www.youtube.com/watch?v=RerJnz42KtE&

**Comment by quidsup** [comment]
I've added a few extra lists now.
There's a few more from ABP EasyList that I can put in.

Cheers

**Comment by ShayBox** [comment]
Thank you :D
