### ISSUE TITLE
Blocked.php not showing blocked sites

### ISSUE THREAD

**Issue by fernfrost** [quidsup/notrack#110]
Blocked.php does not show blocked sites. Blocked sites do however show up on home and stats page.

![blocked_php](https://cloud.githubusercontent.com/assets/11902905/18066407/9c5430aa-6e38-11e6-8578-4dede04cdb78.png)

![home](https://cloud.githubusercontent.com/assets/11902905/18066390/8ee82c1e-6e38-11e6-8e90-b959d0bc41e8.png)

![stats](https://cloud.githubusercontent.com/assets/11902905/18066397/95d696d2-6e38-11e6-82f5-3d173366cdc6.png)

**Comment by fernfrost** [comment]
Should mention that this is a clean install running on raspberry pi 3

**Comment by quidsup** [comment]
Has it worked at all?
The log file gets purged and cached during the day on Monday
The five entries could be access attempts to the /admin or favicon
`cat /var/log/lighttpd/access.log ` will soon tell you

There are two different sources being read:
stats.php reads DNS log
blocked.php reads lighttpd access log

I think some programs / scripts recognise when the IP has been tampered with and then refuse to make a connection (hence the lack of entries in blocked.php)

**Comment by fernfrost** [comment]
Yes its been working fine running on my pi 2 for weeks.
To start with it showed blocked TLDs and later on, for a few, days it showed the full path, often ending in *.js, that had been requested.

Checked the .../lighttpd/access.log and there are several get requests that used to show up in blocked.php.

Will try new fresh installs and see if there is any difference

![blocked](https://cloud.githubusercontent.com/assets/11902905/18069711/4ee42e2c-6e49-11e6-94a1-a9271ad948fe.png)


![home](https://cloud.githubusercontent.com/assets/11902905/18069705/4839444a-6e49-11e6-8553-a9a5e9d95434.png)

**Comment by quidsup** [comment]
No need to reinstall, I need to exclude those /admin lines on the line count on the index.php

**Comment by fernfrost** [comment]
Did a reinstall on pi 3.
Also repointed the dns server on my router (not sure if that made any difference since all those settings should be inactive after disabling dhcp)

Things are looking better. Still only showing 3 (on blocked) out of 6 (on home). 

![blocked](https://cloud.githubusercontent.com/assets/11902905/18070725/0ec375d0-6e50-11e6-845f-fb0eee76dab1.png)

![home](https://cloud.githubusercontent.com/assets/11902905/18070726/16e46f30-6e50-11e6-89c5-bf2e7b6ddc56.png)


![stats](https://cloud.githubusercontent.com/assets/11902905/18070730/1e4875a0-6e50-11e6-9d4c-777bb8f808cf.png)

**Comment by quidsup** [comment]
Method changed as of v0.8
