### ISSUE TITLE
Dnsmasq using universal time

### ISSUE THREAD

**Issue by fernfrost** [quidsup/notrack#112]
Noticed that dnsmasq uses universal time instead of local time.

Could this be a result of system setup before notrack install or perhaps dnsmasq configuration?

![bash](https://cloud.githubusercontent.com/assets/11902905/18094726/ba439ab4-6ed4-11e6-91e0-4ef186407e36.png)

![stats](https://cloud.githubusercontent.com/assets/11902905/18094724/b830a8fc-6ed4-11e6-829d-b42b89ef2290.png)

**Comment by fernfrost** [comment]
So i was mistaken. It appears that blocked.php reads from lighttpd.

Digging around in /var/log/lighttpd/access.log i found timestamp for "img06.en25.com...." to be 1472567927

Converting this to date in bash gives correct local time. Also tested on https://www.functions-online.com/date.html. However, universal time shown on blocked.php. Search continues....

![bash](https://cloud.githubusercontent.com/assets/11902905/18108411/636faf7e-6f0c-11e6-86be-bb355bcdd28b.png)

![php](https://cloud.githubusercontent.com/assets/11902905/18108423/691ad02a-6f0c-11e6-9130-41f25e4fb5f3.png)

**Comment by quidsup** [comment]
```
$ date
Tue 30 Aug 21:55:27 UTC 2016
```
My system is set to UTC.
I've never actually looked into which time zone is in use. If its always using UTC, then perhaps PHP is going to have to correct for local time?

**Comment by fernfrost** [comment]
I think you are right

Found this that sets timezone for whole script:
bool date_default_timezone_set ( string $timezone_identifier )
http://php.net/manual/en/function.date-default-timezone-set.php

Getting the timezone can be done by

![bash](https://cloud.githubusercontent.com/assets/11902905/18109715/6f3a765c-6f13-11e6-8699-3ded0966658b.png)


The question then becomes where to store it. NoTrack config file to be read into memcache?

**Comment by fernfrost** [comment]
Did a clean install of NoTrack on a Ubuntu Desktop and the timestamps are now displayed with correct local time.

Lost for ideas what could be causing the different behavior.

**Comment by quidsup** [comment]
```
$ sudo dpkg-reconfigure tzdata

Current default time zone: 'Europe/London'
Local time is now:      Thu Sep  1 20:33:11 BST 2016.
Universal Time is now:  Thu Sep  1 19:33:11 UTC 2016.
```

I changed timezone from UTC to BST.
I then went to a blocked site and checked the time - it was still on UTC.
I rebooted Raspbian and then went back to blocked.php
All times had updated to local GMT+1

Looks like PHP adjusts to tzdata setting.
