### ISSUE TITLE
New idea? Page Rules

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#113]
Maybe a way to set page rules, like if i visit speedtest.net, it will redirect me to beta.speedtest.net or (any custom one) like CDN page rules. not sure if its possible, but it would be cool

**Comment by quidsup** [comment]
Are you thinking something like CNAME Records?
https://en.wikipedia.org/wiki/CNAME_record

The feature exists in Dnsmasq, however it needs to be aware of the target system.

> --cname=<cname>,<target>[,<TTL>]
> Return a CNAME record which indicates that <cname> is really <target>. There are significant limitations on the target; it must be a DNS name which is known to dnsmasq from /etc/hosts (or additional hosts files), from DHCP, from --interface-name or from another --cname. If the target does not satisfy this criteria, the whole cname is ignored. The cname must be unique, but it is permissable to have more than one cname pointing to the same target.

Try it out and let me know if it works for you.
`dig beta.speedtest.net`
Take a note of the IP from the A / AAAA record

`$ sudo nano /etc/dnsmasq.d/test.list`
```
server=/beta.speedtest.net/1.2.3.4
cname=speedtest.net,beta.speedtest.net
```
`sudo service dnsmasq restart`

If dnsmasq fails to restart then you need to edit the test.list or # comment out the line
