### ISSUE TITLE
DHCP leases show future date

### ISSUE THREAD

**Issue by leeHD2016** [quidsup/notrack#114]
![notrack](https://cloud.githubusercontent.com/assets/21345759/18103971/cbf8cea2-6ef0-11e6-94c5-33dc86783c49.png)

The "DHCP leases" page shows date of request as tomorrow's date. System date is set correctly, all other date references in NoTrack appear correctly. Have run "sudo dpkg-reconfigure tzdata" made no difference. 

Best wishes

**Comment by fernfrost** [comment]
Looking at /var/lib/misc/dnsmasq.leases and date formatting "d M Y \- H:i:s" looks correct.
Perhaps "Date of Request" should be eg "Valid Until" or "Date of Release"?

**Comment by leeHD2016** [comment]
Just changed the lease time to 72h in /etc/dnsmasq.conf and the "Date of request" has changed to the 2nd Sept 2016. So yes it appears to be an incorrect label.
