### ISSUE TITLE
Submit button on stats page resets the form

### ISSUE THREAD

**Issue by mintyfreshpenguin** [quidsup/notrack#117]
Changing a filter on the stats page automatically updates the results. Clicking submit resets the page. 
![screenshot at 2016-09-01 21 28 31](https://cloud.githubusercontent.com/assets/21345759/18183178/1295bd48-708b-11e6-8f32-6d1c89b1b6f1.png)

**Comment by ShayBox** [comment]
Wow you block alot

**Comment by leeHD2016** [comment]
My block list has some 35k domains. I'm pretty sure I saw a screenshot from someone who was blocking 68k+. Can't find it now though. How many are you blocking.

**Comment by duramato** [comment]
Bit off topic lol, 73k here
