### ISSUE TITLE
Idea Suggestion, Insanity Mode

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#119]
Not sure if this would be too big of a project, or easy.
But a way to enable a "Insanity Mode" that will stop the block list mode, and block EVERY website, then any website you want to visit you have to whitelist. Wouldn't get a lot of use, but a cool idea for a rainy day. Maybe even like a default NoTrack Whitelist List that whitelist website's that are known good or are a higher rating on like ICANN. neat idea

**Comment by Serkan-devel** [comment]
Internet explorer on windows server has that feature

**Comment by Quacky2200** [comment]
Sure this would just be a case of just having a whitelist on and a blacklist off, meaning the server will only accept whistlisted domains? I think that's the whole idea of just a whitelist...right? I don't think it should be called 'insanity mode' at all, that takes it a bit far
