### ISSUE TITLE
Doubbleclick requesting alot

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#12]
Found my 3rd top DNS query "l.doubleclick.net" was requested 206 times in the past day... the top 2 being my Mega sync and deluge torrent... but when i go to the website, it doesnt exist so. idk wanted to report it

**Comment by quidsup** [comment]
Doubleclick is Google's main ad serving domain, but they also do some tracking with it too.
Totally blocking it will break Google shopping search, and some of the main search results. On a purely selfish note blocking it will deprive me of ad revenue on YouTube.
My personal option is to white list it on some websites with uBlock browser add-on.

It's easy enough to block with the black list in /etc/notrack/blacklist.txt 
I'm still unsure whether I want it totally blocked

**Comment by ShayBox** [comment]
Ill leave it alone myself, i use the google shopping search, and watch alot of youtube so, yea
