### ISSUE TITLE
Bug: Freezing when updating

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#123]
I've done this a few times now, when i add something to the whitelist, then update the blocklist, i go and force update, which will cause it to freeze because its still updating in the background, maybe add a notification when you try to update and there's a process running.

**Comment by quidsup** [comment]
I've taken the simple option for the moment of preventing two scripts running at the same time
```
$ sudo notrack 
Error. NoTrack already running under Pid 1234
```
