### ISSUE TITLE
NoTrack not respecting TLD blocking

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#124]
![image](http://lol.doyou.bid/03rCI.png)
As you can see .ga is not enabled for blocking but it gets blocked

![image](http://lol.doyou.bid/53P4c.png)
going to the DNS Status it shows it got blocked by the tld blocklist

![image](http://lol.doyou.bid/wbuZ2.png)

This on the the latest git version

**Comment by ShayBox** [comment]
I assume the list isn't fully processed or the description is just saying that because it was blocked, not sure though

**Comment by quidsup** [comment]
```
;; QUESTION SECTION:
;abaiapirata.ga.                        IN      A

;; ANSWER SECTION:
abaiapirata.ga.         14320   IN      A       173.242.118.195

```
I tried going to the IP and got Rickrolled

Tried http://abaiapirata.ga and got blocked
Tried https://abaiapirata.ga and opened something. Im not familiar with the site and didn't progress any further

**Comment by duramato** [comment]
Sorry about that, the rickroll is intended in IP access. the site should show a little player nothing fancy.

**Comment by duramato** [comment]
Well it isn't fixed, I was just explaning how it works, the sorry was about the rickroll lol. The web server is designed to respond with a rickroll to non configured adresses/direct ip

**Comment by quidsup** [comment]
It works if you go via https://abaiapirata.ga/

I checked how the web server functions and it pushes a 301 permanent redirect to https when you access via http.

![screenshot_20160915_204127](https://cloud.githubusercontent.com/assets/16313154/18565062/32a937ee-7b86-11e6-8bec-3afbdccb2dc3.png)

I have the same behaviour on my website, so I tried the same thing with blocking .net and whitelisted my site. It worked fine.

As far as I can tell NoTrack is doing exactly what it should do.

**Comment by duramato** [comment]
But the thing is i didn't had .ga domain blocked and whitelisted mine, i disable .ga blocking and it still blocks it.

To try i just went on google and searched for .ga , browsed to the first result and:

![image](https://cloud.githubusercontent.com/assets/10121067/18565825/46448ea4-7b89-11e6-8ac1-1c0d54fc7537.png)

**Comment by duramato** [comment]
And here it is saying it has been blocked by the TLD block list
![image](https://cloud.githubusercontent.com/assets/10121067/18566047/3a8c161c-7b8a-11e6-9ada-902f3f3576a5.png)

**Comment by duramato** [comment]
Mmm i just tried another domain that is on the TLD default blocked and its blocking eventough it's disabled.

![image](https://cloud.githubusercontent.com/assets/10121067/18566339/65c52ff2-7b8b-11e6-97b8-fbf3025b4878.png)

![image](https://cloud.githubusercontent.com/assets/10121067/18566346/7088f996-7b8b-11e6-889c-76d00e7ead35.png)

![image](https://cloud.githubusercontent.com/assets/10121067/18566364/807f8068-7b8b-11e6-99d9-f28d5106866d.png)

Can't understand what's up, but is certaintly not right..

**Comment by quidsup** [comment]
Did you run Update Blocklist after changing it?

**Comment by duramato** [comment]
Yes, and since then i've ran the Update blocklists multiple times too

**Comment by quidsup** [comment]
My mistake I missed a . in the DomainWhiteList array
```
if [[ $Line =~ ^\.([A-Za-z0-9\-]+)[[:space:]]?#?(.*)$ ]]; then
  DomainWhiteList[".${BASH_REMATCH[1]}"]=true #Add domain to associative array      
fi
```

**Comment by duramato** [comment]
Ok now it's working again! :)
