### ISSUE TITLE
Add support for cedia's malware domain list

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#126]
http://mirror.cedia.org.ec/malwaredomains/

**Comment by quidsup** [comment]
List added. I added support for dealing with compressed zip files and lists in CSV form.

@duramato have you got any suggestions for the description to use in config.php?
Google translate was useless and I don't understand what Cedia is
Thanks

**Comment by duramato** [comment]
CEDIA is and Ecuador organization (for internet advances in ecuador blah blah) which afaik provides the public list of Malware Domains, and some other like the `immortal domains` one (which may be usefull to add too), and several others.
But besides that i don't know much more info sorry.

**Comment by quidsup** [comment]
No problem, that helps a bit.
I thought that immortal domains was in the `domains.zip` file, but its not. Ok not a problem I'll add it in later.
Perhaps the immortal domains should be an on-by-default list
