### ISSUE TITLE
Admin folder

### ISSUE THREAD

**Issue by LucasRoot** [quidsup/notrack#13]
I do know this is useless, but I use my RPi as webserver, and the folder "admin" is alredy occupied.
So we could change the folder "admin" for "notrack" in the lighttpd.conf

**Comment by quidsup** [comment]
I see your point, but on the other hand NoTrack admin folder contains details you probably don't want to be seen from outside of your network.
Personally I would be looking at either running a second RPi or running the NoTrack admin on second instance of lighttpd using a different port.
