### ISSUE TITLE
Blocked.php Load_Access_Log regex

### ISSUE THREAD

**Issue by fernfrost** [quidsup/notrack#132]
The regex in Load_Access_Log on blocked.php doesnt catch the following requests:

- 1473699680|aftonbladet-se.c.richmetrics.com|GET /log?type=page&sn=1&ct=7&pi=ODEHY8HN7D7A&mk=AFTDPPML3FH1&wn=aftonbladet.se&ui=O7ZT92DXYONQ&av=x1.14.0-rc1-JS&ae=1&pc=0&tz=-120&ca=ettan&ed=0&ln=en-US&co=1&ru=1&pd=1840x21448&sd=1920x1080&wd=1855x966&ws=0x0&eu=http%3A%2F%2Fwww.aftonbladet.se%2F&vi=ODEHY8H8MI4L HTTP/1.1|200|76

- 1473782459|static.hotjar.com|GET /c/hotjar-9766.js?sv=3&_=1473782456388 HTTP/1.1|200|76
 
- 1473801322|panel2.research-int.se|GET /0/RI-Panel/pixel/set_panel2.html?440687453__!__http://sifomedia.aftonbladet.se__!__&Typ=panelonly-desktop&Sajt=aftonbladet&Sektion=ettan HTTP/1.1|200|76

Edited the regex slightly to catch everything between "GET" and "HTTP":
/^(\d{1,23})\|([A-Za-z0-9\-\.]{2,253})\|(GET|POST)\s((?!\/admin|\/favicon\.ico).*)\sHTTP\/\d\.\d\|200`

Testing it on https://regex101.com/ it grabs everything correctly but when used in preg_match it returns no match.

Thoughts?

**Comment by quidsup** [comment]
I think the problem was missing = out of Regex matches. Matching on non-whitespace is better

**Comment by quidsup** [comment]
Method changed as ov v0.8
