### ISSUE TITLE
Add yhosts as a list for blocking chinese adverts/malware

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#134]
https://github.com/vokins/yhosts are group of hosts files lists which block several stuff from adverts/trackers to malware. Mainly covering chinese sites/hosted

**Note:** The project on github is written ~100% in chinese but it can easily be understood by a right click translate on chrome or similiar

**Comment by Serkan-devel** [comment]
The blocklist seems legit. I found lots of wondershare sites that need to be blocked.
@quidsup can you implement this list like you did <a href="https://github.com/quidsup/notrack/issues/50">here</a>?

**Comment by quidsup** [comment]
block list added

**Comment by duramato** [comment]
I just noticed something the global list you used incluedes this one https://github.com/vokins/yhosts/blob/master/data/active.txt which has hosts for software activation, which is something totally unwanted imo. Maybe , i don't know if possible, add each list as a source for yhosts in NoTrack and NoTrack could make a list out of them?
