### ISSUE TITLE
Report window not working on certain domains

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#135]
While trying to use the"Report" window on the dns stats page, on the domain `api-b.so.lianmeng.360.cn`, i noticed it wasn't showing up, i took a quick notice in the browser's console and noticed it was erroring, pic bellow:

![image](https://cloud.githubusercontent.com/assets/10121067/18596665/42007790-7c42-11e6-9ddc-55cd86aa52ca.png)

**Comment by quidsup** [comment]
Another mistake on the regex matches, it was only looking for 1-9 instead of 0-9
