### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by Incrementing** [quidsup/notrack#136]
Having one of these four sub-domains blocked causes issues with the Skype App.
I have no issue with calling and chatting via PM but I can't create group chats or talk in group chats.
I can be added to a group chat if I'm already in a private call but I can't see the other person that was added nor can I send/receive messages.

Sub-Domains:
`apps.skype.com
config.skype.com
pipe.skype.com 
pricelist.skype.com`

**Comment by Incrementing** [comment]
Unblocked pipe.skype.com and still no change. 
I'm now unlocking config.skype.com and I'll let you know the out come...

**Comment by duramato** [comment]
I actually experienced this before, and just tought it was mikerowsoft's buggy software at fault lol

Try and see if you can catch all TLDs skype connects and unblocking one by one maybe, also it may be one of NoTrack's 3rd party lists at fault (or you only use NoTrack's ones?)

**Comment by Quacky2200** [comment]
How about turning off the filtering/use Wireshark to catch all that Skype uses (don't have any browsers or other web services open) rather than unblocking one by one?

**Comment by quidsup** [comment]
Its very hard understanding all the Microsoft domains, there was a constant stream of connections to those Skype domains in Windows 10... Despite the fact it was fresh install and didn't have Skype installed.

The simplest option might be to whitelist both` skype.com` and `microsoft.com `

**Comment by Incrementing** [comment]
Yes @duramato I'm using just NoTrack's lists.
And yeah @quidsup, I'll have to unblock skype.com and microsoft.com.

**Comment by Serkan-devel** [comment]
@Incrementing does skype still work if you block spynetalt.microsoft.com ?

**Comment by Incrementing** [comment]
@Serkan-devel I'll have a look.

**Comment by Serkan-devel** [comment]
@Incrementing If you block apps.skype.com It will block ads

**Comment by Incrementing** [comment]
@Serkan-devel I've already got apps.skype.com block in the "Restituted Sites" section of "Internet Options".
