### ISSUE TITLE
Share notrack.conf between bash and php

### ISSUE THREAD

**Issue by fernfrost** [quidsup/notrack#137]
Looking at a dhcp config page and will need to utilize notrack.conf

Thinking of how to share config between bash and php. 
It could be done using built-in php function parse_ini_file and bash function source.

parse_ini_file will return an associative array like:

`Array ( [NetDev] => enp0s3 [IPVersion] => IPv4 [BlockMessage] => pixel [Search] => DuckDuckGo [SearchUrl] => https://duckduckgo.com/?q= [WhoIs] => Who.is [WhoIsUrl] => https://who.is/whois/ [Username] => [Password] => [Delay] => 30 [Suppress] => [bl_custom] => [bl_notrack] => 1 [bl_tld] => 1 [bl_qmalware] => 1 [bl_hexxium] => 1 [bl_disconnectmalvertising] => 0 [bl_easylist] => 0 [bl_easyprivacy] => 0 [bl_fbannoyance] => 0 [bl_fbenhanced] => 0 [bl_fbsocial] => 0 [bl_hphosts] => 0 [bl_malwaredomainlist] => 0 [bl_malwaredomains] => 0 [bl_pglyoyo] => 0 [bl_someonewhocares] => 0 [bl_spam404] => 0 [bl_swissransom] => 0 [bl_swisszeus] => 0 [bl_winhelp2002] => 0 [bl_areasy] => 0 [bl_chneasy] => 0 [bl_deueasy] => 0 [bl_dnkeasy] => 0 [bl_ruseasy] => 0 [bl_fblatin] => 0 [LatestVersion] => 0.7.17 )`

and bash source will simply import the variables.

Writing to config file from php i think would have to be done through ntrk-exec...

parse_ini_file splits key-value pairs on "=" so any strings would have to be enclosed in quotation.

Your thoughts?

**Comment by quidsup** [comment]
I originally used the parse_ini_file, but I switched to the current method in order to carry out error and range checking. Never trust user input.

You have to check if any values are missing, e.g. when new block lists are added.
In terms of number of lines there isn't much between the current method and parse_ini_file
