### ISSUE TITLE
Idea: use SQL to store DNS logs

### ISSUE THREAD

**Issue by quidsup** [quidsup/notrack#141]
It was suggested a while back that I use SQL for storing the log files. The only reason I didn't was lack of knowledge.
Having pushed the regex further and increased the complexity of reading the DNS log file its all too evident that performance is rubbish, particularly once you pass 5000 lines and using an RPi2.

I've started learning how to integrate MariaDB and PHP in a VM with the intention of using it on my web server.

I propose using MariaDB to store current DNS log file and all historic log files.

Ideas:
DB for Current Day, containing rows: Time, System, Request, Result (allowed/blocked/local)

DB for Historic data, containing rows: System, Request, Result, Number of queries
Should it be one DB per day?

A backend script will need running once every few minutes to load data from the live DNS log into SQL.
Daily script will need to remove data from Current Day DB and load it into an Historical DB.

The functionality and regex I've written in queries.php > load_todaylog() could be re-used for a backend script.

It would be nice if there was a way of uploading historical logs into SQL as mine date back to the beginning of the year.

In order to prevent SQL injection attacks any user queries made to the SQL server must never be parsed directly from PHP, they should be filtered for the expected input.

Any other thoughts?

**Comment by quidsup** [comment]
Taken from http://stackoverflow.com/questions/17997558/bash-script-to-insert-values-in-mysql

```
#!/bin/bash
inputfile="test.txt"
cat $inputfile | while read ip mac server; do
    echo "INSERT INTO test (IP,MAC,SERVER) VALUES ('$ip', '$mac', '$server');"
done | mysql -uroot -ptest test;
```

Forms the basis of reading a log file and writing the output to mysql

**Comment by Serkan-devel** [comment]
Use PostgreSQL. It's faster

**Comment by quidsup** [comment]
http://nghenglim.github.io/PostgreSQL-9.5.0-vs-MariaDB-10.1.11-vs-MySQL-5.7.0-year-2016/?time=1
Interesting, MariaDB has the edge on writing, I was about to thats a negligible factor, but then again writing could be a bigger requirement than reading.

When I was messing around on the PHP side I was using mysqli class, is that the same thing for PostgreSQL?
I haven't done any research and Im about to log off for the day

Cheers

**Comment by Quacky2200** [comment]
It's up to you how you implement it but I have found that MySQLi for PHP is OK, what's better though is to use [PDO](http://php.net/manual/en/book.pdo.php). It allows you to put your results into an [MVC-like object](https://phpdelusions.net/pdo#fetch) and/or [associative array](http://php.net/manual/en/pdo.query.php#example-1044). You also '[prepare](http://php.net/manual/en/pdo.prepare.php#example-1042)' statements to prevent SQL injection. However - this is assuming you want an SQL server (good for tons and tons of DNS queries). I would personally use a MySQL server so that you can allow people the choice to keep tons of data or little-to-none so that you have the performance when needed. Also, taking note of using DELETE/CASCADE features to delete old data.

I have used a similar MVC approach in my university project. If you wish, take a look at this [User](https://github.com/shaungeorge/facebook_analyser/blob/master/engine/templates/FacebookAnalyser/models/User.php) and [Results](https://github.com/shaungeorge/facebook_analyser/blob/master/engine/templates/FacebookAnalyser/models/Result.php) object that uses a [ReflectiveObject](https://github.com/shaungeorge/facebook_analyser/blob/master/engine/structure/ReflectiveObject.php) class (basic import/export of an associative array into an object). The User MVC does not use PDO directly but it still imports a Facebook user into itself, whereas the Result MVC has quite a few PDO things.

**Comment by Serkan-devel** [comment]
Due to this project being set in (more or less) embedded environments (raspberry pi's) would it make sense to use sqlite as database?

**Comment by duramato** [comment]
@quidsup any instructions on how to test the mysql implemntation?
IMO i would have gone with a sqlite implementation

**Comment by quidsup** [comment]
I appreciate what you're saying, but I went with system I managed to get my head around first.
Have a look in the /scripts folder
sqlupgrade.txt contains the commands I used to get mysql up and running.
Follow it as far creating the live table.

live.sh is the script file for processing /var/logs/notrack.log file and loading the data into mysql
At the moment live.sh has to be run manually, and it doesn't flush the log file.

My intention is to have it run once every 10 or 15 minutes with a cron job.

/admin/queries2.php is the new page for reading mysql

**Comment by quidsup** [comment]
live.sh is now renamed to ntrk-parse.sh

Updated instructions have been added to sqlupgrade.txt on how to make ntrk-parse a cronjob
I've added ntrk-parse to ntrk-upgrade (Run the upgrade twice)

Outstanding jobs:

- [ ] Automate commands listed in sqlupgrade.txt
- [ ] Add Historic view to queries2.php
- [ ] Add ability to purge Historic and Live tables to config.php
- [ ] Add Historic date count to config.php
- [ ] Script to parse old log files into Historic table

**Comment by quidsup** [comment]
If any early testers want to try it out you can do so by:
Run upgrade twice
Run `bash /notrack/newinstall.sh -sql`

**The old DNS log archiving will be stopped, so /admin/queries.php will no longer work**
You will have to manually type the new page **/admin/queries2.php**

I'm plan to push an interim upgrade, so you won't have run the upgrader twice

**Comment by duramato** [comment]
```
# /usr/local/sbin/ntrk-parse
Not much in /var/log/notrack.log, exiting
```
Normal? It does have contents

**Comment by quidsup** [comment]
I throttle at 200 lines, looks like that's too high

**Comment by quidsup** [comment]
I'll push an update that will reduce the minimum to 50 lines.
Do you want experiment on your system to see what effect reducing the cron job down has?
`/etc/cron.d/ntrk-parse `

I did add a check (untested) to see if ntrk-parse is already running. In theory if the cron interval is too short it won't matter if the previous job is still running.

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/19419525/67d114e2-93d1-11e6-8810-f2dc985dd61b.png)

**Comment by quidsup** [comment]
You won't have any Historic data until 4:20AM or 25 hours after the first log entry, whichever comes first.
But at least its handling the error safely.

I don't know how best to handle old historic log files because there is too much detail ripped out of them.
I could use a fake time and IP of 0.0.0.0?

**Comment by Quacky2200** [comment]
I'm not too sure what you mean by 'too much detail ripped out of them' but you should never fake the data going into the system, even if it's old. 

I'm also a bit unsure as to why you'd limit any data being stored? 
Did you make a [relational database](https://code.tutsplus.com/tutorials/relational-databases-for-dummies--net-30244)? You would be able to store more information without multiple bits of data using [primary and foreign keys](http://www.bbc.co.uk/education/guides/zvq634j/revision/2)

Also, when you mentioned on your YT video that you were surprised; MySQL is specifically made for data access, it has to be able to handle a lot of data and to query them quickly whereas the file log you had was dependent on FS and CPU speed for reading and parsing, something of which a Raspberry Pi is limited in. MySQL stores a lot of its data very efficiently, often caching to memory when required and the use of different data structures or algorithms for searching, indexing, sorting, etc. 

You may be using InnoDB for the storage in your MySQL database, these use the B+ tree data structure, you may find this interesting to read [B+ tree Wikipedia](https://en.wikipedia.org/wiki/B%2B_tree#Algorithms) or more specifically [B+ tree algorithms](https://en.wikipedia.org/wiki/B%2B_tree#Algorithms)

I know people may hate Wikipedia but most mathematical/computer science topics do not really get edited at all and Wikipedia always doubts anonymous changes...Just don't reference Wikipedia in an academic assignment...

On another note, if they keep putting all these Computer Science topics in GCSE and they teach kids in primary to program, I will be out of a job by the time they reach college o.0

**Comment by duramato** [comment]
Is it possible to have some sort of ID to identify specific machines? For example as i'm running  NoTrack remotly all i see normally is one ip adress, my home one. 
For the "Sites Blocked" page you could use the user-agent as you know it from lighttpd logs, but on the dns queries i don't know.

**Comment by quidsup** [comment]
The old log files were reduced down to: Query response, and Result (ie allowed, blocked, local)
This was done in order to speed up loading and processing.

New method with SQL has the columns: Key | Date Time | System | DNS Query | Result
Date will be known from the log file date, however we are missing Time and System.

There's a difference between DNS Query Request and Query response, however I didn't work out how to program the log parser to read the Queries and look for what happened in the response until very recently.

The information being stored now in the relational database covers the useful data from the Dnsmasq log.
Subdomain supression is carried out by the backend log parser as per the users settings.
Although it means it can't be retrospectively changed, however it does improve performance for the frontend web view.

I'm using two tables - Live and Historic, data in the Live table is only kept for one day, after that its copied over to the Historic table and given a new primary key.
My thinking was the focus is more on "today" rather than Historic data.

I didn't know what performance to expect from a RPi and it still amazes what those little systems are capable of.

**Comment by quidsup** [comment]
@duramato I was thinking of using /etc/localhosts.list
I've added all my systems in, e.g. `192.168.1.2   nas.local`

**Comment by duramato** [comment]
That won't suit my case afaik, as i'm in a remote install

**Comment by Quacky2200** [comment]
I would have just had a table with all the requests then instead of copying over data from tables, you can just select the results for a date you want (e.g. today).

`SELECT * FROM table WHERE DATE(timestamp_field) = CURDATE();`

Personally I would have put in a list of hosts that can have their own identity | ID | IP Address | Host Name |

Also, a table for domains and then it would literally just be a case of an intersection table called 'requests' that reference the domain foreign key and host foreign key

**Comment by quidsup** [comment]
Its ready for early adopters.
run `bash install.sh -sql`

@duramato and anyone else already running the new version you will still need to run install.sh -sql because I've added more tables.

**Comment by duramato** [comment]
https://gist.github.com/duramato/209678aae1d81a1646841b9af8fb5f6e
```
fbenhanced in date. Not downloading
Processing list fbenhanced
 100%
ERROR 1045 (28000) at line 1: Access denied for user 'ntrk'@'localhost' (using password: YES)
Finished processing fbenhanced
```

**Comment by quidsup** [comment]
I forgot to write one line in my notes about granting file privileges. I've added it to the installer not.

@duramato 
`sudo mysql --user=root -p -e "GRANT FILE ON *.* TO 'ntrk'@'localhost';" `

**Comment by duramato** [comment]
```
:~# sudo mysql --user=root -p -e "GRANT FILE ON *.* TO 'ntrk'@'localhost';"
Enter password:
ERROR 1290 (HY000) at line 1: The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement
```

**Comment by quidsup** [comment]
Im going to have to take a guess because I didn't run into that problem in Debian or Ubuntu

`sudo mysql --user=root -p -e " FLUSH PRIVILEGES;"`
Then rerun the previous command

**Comment by Serkan-devel** [comment]
I think it would be better to use mariadb as database. It's fork of mysql which can be used as a drop-in replacement for it. When oracle bought sun (the former owners of mysql) most of the core developers forked the project and made mariadb. While mysql removes features and caters mostly to paying customers, mariadb is completely open source, is faster and can do more than mysql enterprise.
They respond to bugs and patch then quicker than their upstream and is more stable.

One problem would be that there isn't an official arm build (for raspberry pi, ect...). They say you can build it from source but when trying to install mysql on a alpine-docker image on a raspberry pi, it installes mariadb correctly

![image](https://cloud.githubusercontent.com/assets/16866642/19627577/19305fae-994a-11e6-8564-8b506b2c0b0e.png)

php-files for use to connect to databases don't need to be re-written.
And I don't think it will brake workflows

**Comment by quidsup** [comment]
Thats why I chose Mariadb over mysql. There is deb package available in Raspbian Jessie and Stretch
