### ISSUE TITLE
Block YouTube Ads?

### ISSUE THREAD

**Issue by 12nick12** [quidsup/notrack#147]
I was wondering if there'd be a way to block YouTube Ads? Pi-Hole seems to be able to do it.

**Comment by mintyfreshpenguin** [comment]
Have you tried a custom block list?

**Comment by 12nick12** [comment]
No. Do you know what domains I would block?

**Comment by quidsup** [comment]
Your can add those to your custom blacklist in /admin/config.php

**Comment by mintyfreshpenguin** [comment]
Hi Quidsup I don't seem to have /admin - on build 0.7.17  So I added the domains to /etc/notrack/blacklist.txt. 

If I created a youtube.csv or youtube.txt in /etc/notrack/ would NoTrack process it as it does all the other files in this directory?

**Comment by mintyfreshpenguin** [comment]
@12nick12 I linked to a couple small lists in my earlier post to get you started.

**Comment by duramato** [comment]
/admin/config.php endpoint, aka `ip_adress/admin/config.php`

**Comment by mintyfreshpenguin** [comment]
@duramato Ah I see, through the browser. I was looking in the file system. Thank you.

**Comment by mintyfreshpenguin** [comment]
Admittedly it's been less than 24hrs but, adding those domains to the file "blacklist.txt" seems to have done the trick.I haven't seen an ad in the browser at all.

The android app is still getting a few through but the quantity and frequency is greatly reduced. 

Generally I don't adblock platforms like YT. I know it's how the content creators make their dollar and like to support their hard work. I was interested to see how difficult Google tried to make adblocking.
