### ISSUE TITLE
Where is config menu gone? v07.18

### ISSUE THREAD

**Issue by mintyfreshpenguin** [quidsup/notrack#149]
So just upgraded to the latest release v07.18 and I can't access the config menu. All I can see is a "no Track" link which takes me to the admin page, and a rather large "cog" that offers options to restart, update and shutdown. 
![screenshot at 2016-10-19 10 20 21](https://cloud.githubusercontent.com/assets/21345759/19512979/447cad46-95e6-11e6-8719-eca576b1f5ac.png)

**Comment by duramato** [comment]
You tried a cache refresh F5+ctrl

**Comment by mintyfreshpenguin** [comment]
Yep that did it, I feel like such a wally. Thank you. Nice new menu :)
