### ISSUE TITLE
NoTrack not blocking?

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#151]
When acessing a blocked page, it queries the dns server , it responds with NoTrack's adress
Images : 
Page that should be blocked: https://lol.doyou.bid/SV1hI.png
DNS query: https://lol.doyou.bid/Y4yiH.png (IP adresses cut on porpuse, but they are my home and the NoTracks one respectivly)

**Comment by quidsup** [comment]
Looks like the DNS lookup has successfully returned the NoTrack IP.
If you were to `ping settings.crashlytics.com` it will return NoTrack IP

Perhaps the IP for crashlytics has been hardcoded into the originating site / app as a means of circumventing blockers?
What was the originating site / app?

**Comment by duramato** [comment]
I tried accessing the site directly, this was only an example, Google's advertising I noticed isn't beeing blocked, eventough dnsmasq returns no track's iP in the dns query

**Comment by quidsup** [comment]
Have you got a Secondary DNS server set on your main system?

All my systems are configured to use a Primary DNS server of 192.168.x.y (NoTrack IP), and no Secondary DNS server

**Comment by duramato** [comment]
Yes Google's, but it's secondary should only use it if the first fails afaik, and NoTrack receives the dns queries

**Comment by quidsup** [comment]
Its not quite as simple as that, when I've looked at the log results in Dnsmasq it seems to make 25% of queries to primary and 75% to secondary.

I don't have log results for my main system, but if something like that happens then it will completly circumvent the blocking measures of NoTrack.

Delete the secondary DNS from your main system.

**Comment by duramato** [comment]
Seems it was that, i really don't like having to rely on just one DNS server, if it goes down bye bye any domain based "internet acess"

**Comment by quidsup** [comment]
How about having a secondary NoTrack device?
