### ISSUE TITLE
There was an error running the query

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#155]
I see "There was an error running the query" on a few of the pages and [the home page only has two groups, Status, and Last Updated](https://gyazo.com/c8fa20e652e7550e8e7c63c54b74af63)
I see theres an SQL update, do i have to re-install or something special?

EDIT: After re-running the install.sh file, it installed the DB program and fixed it.

But i did see [this permission error](https://gyazo.com/a1919497c9f13ed0a747ed88ed7a45f6)

Also, [this did not show up until i already re-ran bash install.sh](https://gyazo.com/a928eb53837b5f5832ef971288671fb0)

**Comment by quidsup** [comment]
Ok thats not too much of a problem, I'm guessing you ran the `newinstall.sh` during the early upgrade to SQL.

I'm interested to see if you're still getting this error? https://gyazo.com/a1919497c9f13ed0a747ed88ed7a45f6

`sudo notrack.sh -f`

Is there anything in `/admin/config.php?full`?

If the error is still there, try running:
```
sudo mysql --user=root -p -e "FLUSH PRIVILEGES;"
bash install -sql
```

**Comment by ShayBox** [comment]
I had manually deleted all the files and .old files and re-installed it so it works great this time, but I also noticed... not really related to this issue, [this](https://gyazo.com/070b1b0489bffde4840c5af450fa0181) never shows the real number on [this page](https://gyazo.com/e2b7b26202d48205d9fa552fee70d47f)

**Comment by quidsup** [comment]
Fixed now
