### ISSUE TITLE
Suggestion: refresh repositories before installing dependencies (testcase: raspbian on RPi1)

### ISSUE THREAD

**Issue by samvde** [quidsup/notrack#161]
After installing ontrack I got the following error when browsing the admin console:

> NoTrack requires mysql to be installed
> Run: bash /opt/notrack/install.sh -sql or bash ~/notrack/install.sh -sql (depending where NoTrack folder is located)

I did the installation again and noticed I actually got an error about php5-mysql not being able to be installed. I am using raspbian on the original RPi. I refreshed the installation repositories using:

`apt update`

After this I reinstalled again, all packages including php5-mysql got installed, and the admin console now works.

It could be a nice idea to refresh the repositories before installing, to make dependency handling more robust.

**Comment by quidsup** [comment]
Agreed, line added to install
