### ISSUE TITLE
Block Spotify ads

### ISSUE THREAD

**Issue by Alexrocksdude** [quidsup/notrack#165]
I found a way to block Spotify ads on both mobile and desktop, these need to be added to the blacklist manually, but it would be great for them to be added to the NoTrack default list:

`spclient.wg.spotify.com

sto3.spotify.com

audio-ec.spotify.com

prod.spotify.map.fastlylb.net

ads-fa.spotify.com

analytics.spotify.com

log.spotify.com

adeventtracker.spotify.com

crashdump.spotify.com

www.audio2.spotify.com

audio2.spotify.com

heads-ec.spotify.com`

**Comment by duramato** [comment]
You can send a pull request, the list is here in this repository.

**Comment by Alexrocksdude** [comment]
Added a pull request: https://github.com/quidsup/notrack/pull/166
