### ISSUE TITLE
EasyPrivacy Typo/Not Saving

### ISSUE THREAD

**Issue by jdyx** [quidsup/notrack#17]
With the easy privacy list there is a typo in the input name, reads name="blocklist_easypriacy" should be name="blocklist_easyprivacy", and also there are no if/isset checks in the UpdateBlockListConfig() for easyprivacy so it doesn't save/update. I've manually added them myself and it seems to have fixed it for my set up.

**Comment by quidsup** [comment]
Fixed now. Cheers
