### ISSUE TITLE
add trackers

### ISSUE THREAD

**Issue by facastagnini** [quidsup/notrack#170]
Today I found that some emails came with a tracking pixel. They pointed to `http://t.sidekickopen68.com`

Then google show me that I can getsidekick.com , which takes you to `https://www.hubspot.com/products/sales/sales-tools` 

> HUBSPOT SALES
> Powerful tools to supercharge every stage of your inbound sales process.

**Comment by quidsup** [comment]
Thanks, that provided a lot of linked sites

**Comment by facastagnini** [comment]
You rock man, you managed to find all the related domains!
