### ISSUE TITLE
Skype Breaking

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#174]
Although i know skype domains are blocked for tracking, What would i unblock (whitelist) to get skype web and skype for linux beta to work... i tried whitelisting skype.com but it didn't work

**Comment by mintyfreshpenguin** [comment]
I don't think there is an easy answer - doesn't skype use P2P? You might have to put in some serious screen time.

Looking at the problem from the flip side - how to block skype threw up this interesting post. http://pingtool.org/block-skype-connection/(http://pingtool.org/block-skype-connection/). I've run the dig command and the list still appears current.  Could try whitelisting them? I don't know where the author got the url from or whether it is even correct.

Running the dig command with skype.com resulted with these ip's:
104.40.50.126
23.102.255.237
40.115.34.155
40.121.80.200

Perhaps try Wireshark. Start a call and try a filter for you skype box ip and the udp port skype uses?

**Comment by ShayBox** [comment]
my problem is that i cant login to skype, it cant reach the dns unless i pause notrack and when i unpause it, it signs out again

**Comment by mintyfreshpenguin** [comment]
Sounds like NT could be blocking the authentication hosts that skype uses?

**Comment by quidsup** [comment]
DNS Queries > Today > Time view will help to work out what domains Skype needs.

I think at a minimum the following domains will need to be whitelisted:
live.com 
skype.com 
hotmail.com

**Comment by quidsup** [comment]
Skype domains ublocked
