### ISSUE TITLE
Editing blacklist from GUI does not update blocklists

### ISSUE THREAD

**Issue by manofcolombia** [quidsup/notrack#175]
Yesterday I had added some extra items to my blacklist and discovered that they break google docs. When I went to removed them from the blacklist, I was going to deactivate one by one to find the culprit. Deactivating and manually hitting update blocklist does not update the list. Even deleting the blacklist entries and updating the blocklist does not work. You can update the blocklist and return to the blacklist page and see the entries are still there or you can look at sites blocked and see they are still there. Also, downloading your blacklist.txt still shows all entries even after deletion. 

Running 8.1a, not sure which version of 8.1a because they are both the same version number

**Comment by quidsup** [comment]
I think it might be a permissions issue. Try: `sudo chmod -R 775 /etc/notrack`

**Comment by quidsup** [comment]
If you were able to add sites to the list it could be a Javascript issue.
Have you got anything like noscript preventing access to the .js files in /admin/include

**Comment by manofcolombia** [comment]
I am still able to add sites, but I can not remove any entries. I tried adjusted the permissions as you suggested and this did not resolve the issue.

**Comment by quidsup** [comment]
I'm fairly certain its a Javascript issue, can you check to see if another feature is working or broken please?
Click the **Options** button in the top right-hand side of any page.
It should bring up a dialog box with three buttons.

**Comment by manofcolombia** [comment]
The options button flyout works and I don't have anything in my browser that should be killing JS. Thats how I reboot the VM and such. I have another issue with dnsmasq when i reboot, but I will put that in another thread.

**Comment by quidsup** [comment]
I've tidied up some old code and removed a couple of deprecated functions with b04306b 
I'm not entirely convinced it will fix this issue though.

What happens if you manually call the delete function?
`/admin/config.php?v=black&action=black&do=del&row=1`
will delete the first item in your black list.

**Comment by manofcolombia** [comment]
I forced the upgrade and the delete function does delete it out of the list in the gui, but, even after updating the block lists, the entries still remain in the block list

**Comment by quidsup** [comment]
I'm going to need some more info to fix this. Can you get me the following please:

`php -v`

`notrack --test`

Open the page 
`/admin/config.php?v=black&action=black&do=del&row=1`
Then grab the lighttpd error log
`tail -n 20 /var/log/lighttpd/error.log`

**Comment by manofcolombia** [comment]
[NoTrack.txt](https://github.com/quidsup/notrack/files/603611/NoTrack.txt)


Attached the output. I doubt the log is going to be much use because it is filled with https 
I tried the same del row on the normal http page, but same issue

**Comment by quidsup** [comment]
I tried to replicate your selections with Ubuntu 16.04 server and it worked.
I did wonder if was an issue with older version of PHP, but no that theory is wrong.

Try this command to remove SSL lines from error.log
`grep -v SSL /var/log/lighttpd/error.log`
