### ISSUE TITLE
Custom DNS entires

### ISSUE THREAD

**Issue by calebpaine** [quidsup/notrack#176]
I tried to set this up where my router was the DHCP DNS listing, but could not get it to work. I ended up having my router keep DHCP, but advertising the notrack VM as the DNS host and its working as expected.

Problem is, now none of my DHCP hosts are available by dns (obviously). Not the end of the world, but most importantly I had some custom DNS entries set in my router for statically assigned devices. My router (pfsense) had a simple area to add these, but I see no such option in NoTrack, at least in the gui. Is there a way to do this?

**Comment by quidsup** [comment]
I haven't implemented it in the gui yet, but yes you can add custom entries using `/etc/localhosts.list `

Restart dnsmasq after you make any changes to the file
`sudo systemctl restart dnsmasq`

**Comment by calebpaine** [comment]
Awesome, that'll work for now. A gui to manage that would be nice!
