### ISSUE TITLE
Changes to NoTrack Blocklist

### ISSUE THREAD

**Issue by quidsup** [quidsup/notrack#179]
I have migrated the NoTrack Block List over to a MariaDB SQL Database running on my website. https://quidsup.net/notrack/blocklist.php

The Report site page has also been migrated to a separate table, and I have tightened up on the rules to prevent repeated entries, and I also delayed appearance of new sites on the table. 

I have implemented a GUI administration page on my site, but right now access is limited to one account. I do have the option of expanding access to a select few people.

If you want to add new entries on the block list you can either:

- Add them on the end of the trackers.txt file and open a Pull request. 
- Use bulk submission page on https://quidsup.net/notrack/report.php?view=multisubmit (This is limited to 20 entries at a time currently)
- Use the Report button within NoTrack.

The biggest time saving is not having to worry about putting new sites into alphabetical order. I can have MariaDB do the job, and then copy&paste the file over to Github.

**Comment by r-a-y** [comment]
Nice list! Can you offer an option to download as a HOSTS file?
