### ISSUE TITLE
Whitelist?

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#18]
How would i go about adding adf.ly to the whitelist? i tried adding a line to /etc/notrack/whitelist.txt then running sudo notrack but didn't work.

**Comment by quidsup** [comment]
You're doing the right thing.
I haven't got adf.ly in my list, so I'm guessing its one of the Windows lists you've enabled, like PglYoyo?

I'm away from home for a couple of days and haven't got access to a Linux system.

There is something you can try:
With notrack.sh in the function Process_UnixList127
Replace line 607: Line=${Line:-1}
With: 
Line=$(tr -d '\r' <<< "$Line")

That should strip off the Windows carriage return and make AddSite function correctly check each line of the blocklist against your whitelist

**Comment by quidsup** [comment]
Latest version of notrack.sh should have fixed this issue
