### ISSUE TITLE
Solus install

### ISSUE THREAD

**Issue by quidsup** [quidsup/notrack#180]
Solus uses the eopkg package manager

**Comment by nan0s7** [comment]
Hey I see that this is still open, are you still in need of help? My main PC is running Solus OS at the moment when I'm not in Windows.

**Comment by quidsup** [comment]
I certainly would appreciate it, I didn't really look any further at sorting out this issue

**Comment by nan0s7** [comment]
Sorry about the huge delay; I've been pretty busy. But I have finally gotten around to getting this working in Solus. Currently I'm waiting on getting lighttpd in the repos, just so you know I haven't forgotten about it :P

**Comment by quidsup** [comment]
Closing as this is no longer a priority
