### ISSUE TITLE
Way to temporarly disable NoTrack

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#19]
Theres been a few websites that detect NoTrack even when i whitelist them, and it shows the ads... i can change my name servers or turn off all the blocker lists, but thats a bit annoying every time i want to goto the website, would there be a way to run a command like sudo sh /etc/notrack/disable.sh to temporarly disable notrack for 10mins or something on the admin page? idk just an idea. -D thanks

**Comment by quidsup** [comment]
Nice idea.
I'll take the Admin page option.
It will be simple enough to add the code in ntrk-exec.sh, and then add a pause button to the Admin page

**Comment by quidsup** [comment]
Pause button added to Admin page
