### ISSUE TITLE
Polldaddy.com in the latest update?

### ISSUE THREAD

**Issue by donnchawp** [quidsup/notrack#190]
Hi,

I found polldaddy.com in the latest version of the list at https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt but I think that's in error as it stops your users using the actual website, https://polldaddy.com/

I work on the Polldaddy website. It's used for online polls, surveys and quizzes. It uses cookies to discourage people from cheating in polls (we also use a few other ways of doing this), but also to identify users who are taking part in surveys. Sometimes they leave the survey, and come back to it later. The cookie tells the server where in the survey they stopped.

I would appreciate if you removed the polldaddy.com domain from your list.

Thanks,
Donncha

**Comment by Serkan-devel** [comment]
equestriadaily.com uses polldady on the right side of the page.

Having an adblocker (with the notrack list) on that site removes the pools feature.

**Comment by quidsup** [comment]
I've looked further at what I can see client side. Thanks for the example website @Serkan-devel 

I can see two different cookie life times of per session and one year.
I have no issues with the per session cookie, but one year to complete a survey sounds a little bit too excessive.

Ultimately I don't know what your company does with the information, but from my side I see something which is used in multiple websites, has long life cookies, seems to have audio library being utilised yet doesn't play audio.
The information I see leans more to something with the potential to track users and falls under what I'm trying to prevent.

If your company is keeping the data in house for whatever you need to prevent abuse of your services, and you are not selling user data on to 3rd parties, then I am willing to remove polldaddy.com from the blocklist.

**Comment by donnchawp** [comment]
I can see where you're coming from. If it means anything, Polldaddy is owned by Automattic who run WordPress.com, but we're an Irish company so we operate under EU laws which are fairly strict about privacy issues. The long lived cookie you saw is used internally only on the site for our site development so we can tell how users travel around the site. (ie. do they go to the features page before the signup page?) I guarantee we're not tracking users across the web.

The audio library we use is for playing embedded mp3s in polls or surveys, except it uses Flash so it's in dire need of a replacement. That's one of my jobs on the todolist.

Polldaddy polls are used in lots of places including Arstechnica, BBC, Microsoft, NYTimes, IBM, Lego, various newspaper websites, even the Drudge Report.. The US election night was fun with people hammering that poll. :)

**Comment by quidsup** [comment]
Thanks, I've removed polldaddy.com from the blocklist
