### ISSUE TITLE
support.microsoft.com is being blocked

### ISSUE THREAD

**Issue by Freekers** [quidsup/notrack#192]
As per title, support.microsoft.com is being blocked. This was done on request of a user (see issue: #5) but I don't quite understand why. Sure 'diagnostics.support.microsoft.com' should be blocked, but support.microsoft.com should not in my opinion, for example to download hotfixes.

Please consider removing it from the list

Thanks.

**Comment by Rouzax** [comment]
Same issue and even after adding it to the White list it still will not resolve.

**Comment by ShayBox** [comment]
It worked after whitelisting for me, but you have to wait a day or so, pausing/resuming/updating the blocklist doesn't happen instantly, not even close.

**Comment by quidsup** [comment]
site removed

**Comment by allinawislon** [comment]
if you have any problem while opening support.microsoft then open this link
`
<a   href="http://microsofthelpnumbers.com/>
--

Microsoft Helpline
`
