### ISSUE TITLE
option to disable DHCP

### ISSUE THREAD

**Issue by yustmenl** [quidsup/notrack#195]
i would like to keep using the DHCP server of my router, is there a way to disable the DHCP server in no track?

**Comment by quidsup** [comment]
Comment the line `dhcp-range=IP start,IP end,time` in `/etc/dnsmasq.conf`
e.g. `dhcp-range=192.168.0.128,192.168.0.254,24h`

**Comment by quidsup** [comment]
Feature now added to NoTrack v0.9
