### ISSUE TITLE
Worst website i've ever seen

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#199]
This website is the worst I've ever seen, popups, ads, some of the popups play voices and take control of your mouse, its bad. please add to blacklist "nosteam.com.ro"

**Comment by duramato** [comment]
That site is "legit", what needs to be blocked is the advertising networks. Which are blocked to me on NotTrack, just don't from which list since i used them all.

**Comment by quidsup** [comment]
Dare I even look...
Maybe tomorrow

**Comment by cinnamoner** [comment]
@quidsup Might end up using your software. Seems quite capable to me. Congratulations for your efforts. They are much appreciated.

**Comment by ShayBox** [comment]
I've got uBlock Origin with all blocker lists and NoTrack with all blocker lists enabled, and nosteam.ru.com's popups still show up, they must be really good at bypassing them

**Comment by duramato** [comment]
I forgot i also use [Popup Blocker Pro](https://chrome.google.com/webstore/detail/popup-blocker-pro/kiodaajmphnkcajieajajinghpejdjai?utm_source=chrome-app-launcher-info-dialog)

**Comment by jake-cryptic** [comment]
Here are some of the domains:
bigdataexchange.com
http://ixnsmcpdauof.com/
http://mysagagame.com/
http://terrapops.com/

**Comment by quidsup** [comment]
Added a few  popup sites to the blocklist.
It behaved itself after that
