### ISSUE TITLE
DHCP Leases

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#20]
Sorry for the large amount of issues, but when i first got NoTrack you fixed cause i had 2 network interfaces. and DHCP Leases tab was empty, so i though it wasn't in use. but after connecting to my wlan0 hotspot the devices appeared in the DHCP leases list, but i selected eth0 in the installer, and the devices connected to eth0 aren't in the list. i don't know if that's supposed to happen.

**Comment by quidsup** [comment]
No problem, you're catching issues I haven't come across.
DHCP has to be enabled, heres a tutorial I did on YouTube: https://www.youtube.com/watch?v=a5dUJ0SlGP0
(Which reminds me I need to add that to the DHCP page)

As for this issue, the config line in Dnsmasq is disabled by default, so I don't understand how it would become enabled on its own.
Admin DHCP page looks for the file /var/lib/misc/dnsmasq.leases, and will show the contents if it exists.
