### ISSUE TITLE
blocking trafficmanager.net makes .NET core inaccessible and probably more

### ISSUE THREAD

**Issue by Serkan-devel** [quidsup/notrack#201]
Microsoft uses this domain to as an apt repository for .net and probably more.
https://www.microsoft.com/net/core#linuxubuntu

Even though I'm only using the blocklist on my adblocker, it might still cause problems when people want a .net/C#-environment or for running !osu

PS: A German tech-youtuber made a review of this project https://www.youtube.com/watch?v=i4UndCCqRu8

**Comment by quidsup** [comment]
OK I've deleted it out of my master list at the moment, I'll push it across to git later.
Thanks I watched it, but my German is not very good

**Comment by Serkan-devel** [comment]
When will it be pushed to master?
Maybe just whitelist `apt-mo.trafficmanager.net` to the whitelist somehow

**Comment by quidsup** [comment]
Its done. Think it was only a few days after my previous comment
