### ISSUE TITLE
Way to reconfigure target IP

### ISSUE THREAD

**Issue by nielstron** [quidsup/notrack#205]
Hey Quidsup,
I've set up no track at home on a raspberry pi. My router redirects DNS-requests to it. So far everything is fine. The problem is as follows: Notrack answers blocked domains with the ip 127.0.53.53. Yet there is no server/nothing responding! (as the device connected to the router tries to access the ip and not the raspberry pi). Consequently the router uses the alternative DNS server if I try to access blocked domains and the sink-holing effect vanished.

I love this tool and it would help me a great deal if I could set the ip returned for blocked domains to i.e. the ip of the raspberry pi or at least something that responds in any way.

Sincerely

**Comment by quidsup** [comment]
I'm not sure whats caused that, but you can set a custom IP in `/etc/notrack/notrack.conf`
Change IPVersion to an IP address:
e.g. `IPVersion = 192.168.0.2`

Run `notrack --test` to confirm its working
Then `sudo notrack`

**Comment by nielstron** [comment]
Thank you!
I think that this is a basic problem with notrack that should be fixed in the source code.

If the device with notrack is set as the only DNS-Server (or as primary and alternative) the current settings significantly slow down internet browsing because the computer tries to access the invalid ip provided by notrack where there is no responding server. As a result the website is not shown until a time out happens.

Secondly if you set up an alternative DNS-Server this removes the notrack-effect because for every tracking-website the computer (or router) uses the alternative DNS as the ip provided by notrack is invalid.

Sincerely
