### ISSUE TITLE
Outlook/Hotmail free email blocked

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#206]
```
Feb 22 17:14:13 dnsmasq[28746]: query[A] www.hotmail.com from 173.242.118.195
Feb 22 17:14:13 dnsmasq[28746]: forwarded www.hotmail.com to 8.8.8.8
Feb 22 17:14:13 dnsmasq[28746]: reply dispatch.kahuna.glbdns2.microsoft.com is 65.55.185.236
Feb 22 17:14:13 dnsmasq[28746]: reply dispatch.kahuna.glbdns2.microsoft.com is 65.55.118.92
Feb 22 17:14:13 dnsmasq[28746]: query[A] dispatch.kahuna.glbdns2.microsoft.com from 173.242.118.195
Feb 22 17:14:13 dnsmasq[28746]: config dispatch.kahuna.glbdns2.microsoft.com is 172.82.187.143
```
And as the reply domains don't get logged on NoTrack, nor the original query i can't easily whitelist on notrack without going to it's logs.

**Comment by quidsup** [comment]
I'll remove glbdns2.microsoft.com from the blocklist

It still leaves the following blocked:
11870: corpext.msitadfs.glbdns2.microsoft.com #Microsoft
11896: settings.data.glbdns2.microsoft.com #Microsoft
11908: vortex.data.glbdns2.microsoft.com #Microsoft

**Comment by duramato** [comment]
same for 

```
Feb 27 01:21:42 dnsmasq[20947]: query[A] edge-live.outlook.office.com from 173.242.118.195
Feb 27 01:21:42 dnsmasq[20947]: forwarded edge-live.outlook.office.com to 8.8.8.8
Feb 27 01:21:42 dnsmasq[20947]: forwarded edge-live.outlook.office.com to 8.8.4.4
Feb 27 01:21:42 dnsmasq[20947]: reply l-0002.l-msedge.net is 13.107.42.11
Feb 27 01:21:42 dnsmasq[20947]: query[A] outlook-live-com.a-0010.a-msedge.net from 173.242.118.195
Feb 27 01:21:42 dnsmasq[20947]: config outlook-live-com.a-0010.a-msedge.net is 172.82.187.143
```

**Comment by duramato** [comment]
Tinypic is also blocked, ex: http://i45.tinypic.com/2mg8u3k.jpg
```
Feb 28 20:09:08 dnsmasq[4860]: query[A] ne1.wac.v4cdn.net from 173.242.118.195
Feb 28 20:09:08 dnsmasq[4860]: config ne1.wac.v4cdn.net is 172.82.187.143
```

**Comment by quidsup** [comment]
Worked for me, but ok I've been having second thoughts on those Verizon domains v0cdn - v13cdn, and have deleted them now.

Do you want access to the master list?
It would certainly help me out if you were able to do some of the editing and approval of user submitted sites

**Comment by duramato** [comment]
Sure, i can give you a helping hand

**Comment by quidsup** [comment]
I'll have to think of the best way of adding a user.
Its hard coded on the page, so I would either have to allocate you a password, or ask you to make one up and send me the result of it in `php_hash `

I'll email you tomorrow
