### ISSUE TITLE
Items to be whitelisted (cross post from a ticket submitted to my git)

### ISSUE THREAD

**Issue by notracking** [quidsup/notrack#208]
Hi quidsup,

I've been using your list for a while to mangle with several others, one of my users submitted the following hostnames that should not be blocked in our opinion. See [here](https://github.com/notracking/hosts-blocklists/issues/12) for the original bugreport.

(Fixed quidsup) bing.net, virtualearth.net - Bing search and Bing maps(Fixed quidsup) h-cdn.com - HolaCDN - CDN for video delivery. Used for video streaming.
(Fixed quidsup) symcd.com - Symantec CA. Used for verifying SSL certificates.
(Fixed quidsup) performgroup.com - Digital sports content and media group. Domain used for content delivery to other Perform brands. Example, goal.com

**Comment by quidsup** [comment]
bing.net - requires further investigation
virtualearth.net - removed
h-cdn.com - removed
symcd.com - removed
performgroup.com - removed

**Comment by quidsup** [comment]
bing.net will be removed next commit

**Comment by notracking** [comment]
Thanks!
