### ISSUE TITLE
A new UI for NoTrack

### ISSUE THREAD

**Issue by thegreatrazz** [quidsup/notrack#213]
My biggest complaint about NoTrack I have right now is the web UI. It's inconsistent from device to device, it's sluggish (on lower end devices) and it looks quite ugly. I'm offering to redesign it and make it consistent across all HTTP/HTML5 standard compliant web browsers. I would keep the general layout of NoTrack, but have the styling updated to a more modern [Material Design](https://material.io/) inspired look to it.

Here's a preview of what it could look like:
![https://feen.us/vdnyrj.png](https://feen.us/vdnyrj.png)

**Comment by quidsup** [comment]
Sorry I didn't reply sooner. I don't really want any drastic changes to the UI, but I don't mind any tweaks to the CSS to improve the look across devices
