### ISSUE TITLE
Roku Notrack

### ISSUE THREAD

**Issue by Caver1** [quidsup/notrack#216]
When I use Notrack I cannot get any of my channels to connect. Checking the settings in the Roku it says everything is connected fine even the internet. I search the logs and find nothing for Roku blocked.
Otherwise Notrack seems to work great.

**Comment by quidsup** [comment]
There are a few Roku sites in the blocklist, of which I know two were attributed to tracking, but the other two may or may not be tracking.

Put these two sites in your NoTrack whitelist:
mobile.logs.roku.com
scribe.logs.roku.com

**Comment by Caver1** [comment]
Sorry I didn't get back sooner. Thanks for your fast reply and help.
I found out that Roku hard wires Google ISP into the Roku.
So far I haven't been able to get around it.
Thanks again,
Doug
