### ISSUE TITLE
Notrack List causes Windows 10 Event Triggering (131 and 202)

### ISSUE THREAD

**Issue by thexmanxyz** [quidsup/notrack#217]
#### Steps to reproduce this issue
1. Pi-Hole with NoTrack List
2. Activate DNS blocking
3. Check Windows 10 on error message in event management - exist and frequently triggered
4. Deactivate DNS blocking
5. Check Windows 10 on error message in event management - gone and not triggered anymore
6. Possibly do a restart to verify because this triggers the messages extensively if the list is active. 

#### Expected Behaviour
No error messages in windows 10 event management

#### Actual Behaviour
Lots of error messages and warnings in windows 10 event management. 

Event 131: Staging of Metadata. Result=0x0070001 for Container "{00000000-0000-0000-FFFF-FFFFFFFFFFFF}" 
Event 131: Staging of Metadata. Result=0x80070001 for Container "{024C7600-5476-0074-1A4E-003854746C18}".
Event 202: Networklist-Manager - Connectivity Problem

I did my best to translate the error messages from german to english but they are not exactly how they would be on an english Windows 10. I'm not sure if these errors are problematic but they are directly related to device installations so they could possibly be problematic. In what grade I can't really judge. But I just want to let you know that there are possible interferences with the list and the blocking of dns requests with some of the hosts. Both machines are completely different in hardware and had no problems without the blocking and also the event throwing went instantly away after disabling the blocking and one restart.

#### Configuration

**Country** 
Austria

**Machines**
2x Windows 10 Professional both on Creators - Version 1703 (Build 15063.138) | AMD and Sandy Bridge Platform

**Comment by quidsup** [comment]
Error 131 is triggered when Windows 10 is unable to access the following domains:
- dmd.metaservices.microsoft.com
- ssw.live.com
https://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/multiple-errors-in-event-viewer-eventid-131-from/e5054c3b-bc91-4beb-894f-4d0d9f0dd8ca?page=2

They are associated with Microsoft telemetry
http://www.informationsecuritybuzz.com/articles/companies-that-you-trust-are-stealing-from-you/

>     dmd.metaservices.microsoft.com/dms/metadata.svc
>     ssw.live.com/UploadData.aspx
> 
> Both of these contain information about you and your device based on the settings you’ve selected in your Windows 10 privacy settings.

Given the function of the domains I believe it is better to keep them blocked

**Comment by thexmanxyz** [comment]
@quidsup The Error 131 is not the one the really bothers me because it's simply a warning. However the countinous 202 Errors are. I didn't see what DNS block finally triggers the 202. Maybe you keep an eye especially on the 202s. The 131 Error does not seem to be a problem (I just mentioned them because they are also triggered) but with the other one i'm not really sure. So far so good just wanted to let you know :)

**Comment by Atavic** [comment]
>Event 202: Networklist-Manager - Connectivity Problem

That's related to the other one, as windows telemetry can't ping those servers. Connectivity Problems relate to the OS Telemetry, not the user's web connections.

**Comment by Serkan-devel** [comment]
Maybe this could be fixed on NTlite
