### ISSUE TITLE
question: can I install NoTrack on Debian 5.0 router with 256mb of ram

### ISSUE THREAD

**Issue by sgoudelis** [quidsup/notrack#221]
Hello,

I am very interested in installing NoTrack on my router which is an ALIX board with a 500mhz CPU and 256mb of ram. I am already using dnsmasq but I would like to have the MariaDB and php site on NoTrack on another box. Is that possible? Is there a guide to set it up manually ?

**Comment by quidsup** [comment]
There certainly is a manual guide https://github.com/quidsup/notrack/wiki/Custom-Install
I don't know if Debian 5 will have all the dependencies, but you're welcome to try
