### ISSUE TITLE
Wrong block list matching

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#226]
`steamcdn-a.akamaihd.net` is saying it was blocked by Easy List but it isn't part of the list.

`akamaihd.net` on the other hand it's saying corretly which list blocked it.

![image](https://lol.doyou.bid/dsCWA.png)

![image](https://lol.doyou.bid/h4F9H.png
)

**Comment by duramato** [comment]
Another,

![image](https://lol.doyou.bid/mH3Iu.png)

![image](https://lol.doyou.bid/L7ggo.png)

**Comment by quidsup** [comment]
Fixed now
