### ISSUE TITLE
Not detecting chrome on android

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#227]
```Mozilla/5.0 (Linux; Android 7.1.1; Nexus 5X Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36```

![image](https://lol.doyou.bid/q64TQ.png)

And the following are apps using Android's webview(?)
- Mozilla/5.0 (Linux; Android 7.1.1; Nexus 5X Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36 AliApp(AliexpressAndroid/5.3.6) WindVane/8.0.0 AliApp(AE/5.3.6) AE_LANG(pt-PT)
- Mozilla/5.0 (Linux; Android 7.1.1; Nexus 5X Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36 [FBIA/FB4A;FBAV/133.0.0.19.83;]
- Mozilla/5.0 (Linux; Android 7.1.1; Nexus 5X Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36 Instagram 10.31.0 Android (25/7.1.1; 420dpi; 1794x1080; LGE/google; Nexus 5X; bullhead; bullhead; pt_PT)

**Comment by duramato** [comment]
Another one not sure if you want to add,

Spotify's client on windows

![image](https://lol.doyou.bid/4Adh2.png)

**Comment by quidsup** [comment]
Looks more like specific apps on Android that are failing. 
I'm having a similar problem at work at the moment with all these non-standard user-agents.

Have you dot an example of the Spotify user-agent please?

**Comment by duramato** [comment]
- Spotify/105800573 Win32/0 (PC laptop)
- Spotify/8.4.9 Android/25 (Nexus 5X)

**Comment by quidsup** [comment]
Much improved in v0.9
