### ISSUE TITLE
Legit hostname blocked

### ISSUE THREAD

**Issue by notracking** [quidsup/notrack#228]
Hi there,

One of my users reported a false positive, after checking I found that your list was the source of it.
See: https://github.com/notracking/hosts-blocklists/pull/18

Good luck and thanks for maintaining this list!

**Comment by quidsup** [comment]
Updated the database. I'll update the file on Github in a few days.
Thanks

**Comment by notracking** [comment]
And another one was reported: https://github.com/notracking/hosts-blocklists/issues/19
quidsup.txt:0.0.0.0 lithium.com

**Comment by quidsup** [comment]
I've removed lithium for now, but I may re-add it at somepoint because its a mulitpurpose domain for hosting and tracking
