### ISSUE TITLE
Site/Web Interface is not accessible if using install.sh on KDE NEON

### ISSUE THREAD

**Issue by dariusworks** [quidsup/notrack#230]
So In a VM I tried installing by doing same configuration.
One System was Linux Mint (Mate) 32 bit "linuxmint-18.2-mate-32bit" `f706000aba58ed5ef890bdacb01943c107a290a50917c453d45e314a92b74dea` and another
KDE NEON User LTS 64 Bit "neon-userltsedition-20170712-0018-amd64" `1e5081f168999d319244a14cde79a75713ca73d40972c59a1fddd5555089e29a` (SHA256)
As you see, iso images are unaffected.

On Linux Mint, web interface after installation was available to use, mysql_secure_installation was not runned.
On KDE NEON no web interface was available, running mysql_secure_installation (in sudo, which isn't mentioned) still didn't get web interface.

Any possible solutions? (If possible without getting another ISO)

**Comment by StewVed** [comment]
I got this with a proper install of KDE Neon. I think there was some error in systemd and lighttpd?
yes, a little googling suggested that gamin isn't installed, but lighttpd needs it.
try:
sudo apt install gamin
then:
/etc/init.d/lighttpd restart
notrack now works for me!!! wohoooo!!!! (KDE Neon 64-bit - latest updates)

**Comment by dariusworks** [comment]
That **worked**, but now here's the new problem, admin pane cannot be accessed

**Comment by dariusworks** [comment]
On VM that didn't happen, and I think the problem. I think that caused due to using WiFi and/or DHCP.

**Comment by dariusworks** [comment]
That **worked**, but now here's the **new problem**, admin panel (web interface) cannot be accessed, and instead it's blank page with small image
On VM that didn't happen, and I think the problem was caused due to me using WiFi and/or DHCP., I'm not sure why, but even when disconnected from wifi, admin was still not accessible (on chrome and firefox)
Now what causes that?

**Comment by dariusworks** [comment]
**That fixes issue**, and on VM and real hardware it works, but I configurated it to use WIFI with DHCP, And admin page is not showing up (but now blank page with invisible pixel)
Now what causes that?
https://quidsup.net/images/svg/Tux-Puzzled.svg

**Comment by dariusworks** [comment]
@quidsup `sudo apt install gamin` add this so install script would be recommended.
