### ISSUE TITLE
ntrk-parse: not found

### ISSUE THREAD

**Issue by blub4747** [quidsup/notrack#231]
Hello guys,

I am sorry but I had to uninstall notrack.

Here is the way how I uninstalled notrack 
apt-get purge dnsmasq
apt-get purge  lighttpd 
apt-get purge mysql-common 
and finally I removed all four ntr* folders or directories in /sbin.
However I do still get cron msgs  telling the above.
Where do I please need to look to stop these notifications?
Thx, blub4747

**Comment by games647** [comment]
Why didn't you just run the uninstall script? After you uninstalled it manually you can look there to see what do you missed.

**Comment by blub4747** [comment]
Sorry for not including that I already tried to use the uninstall script.
Too bad that I did not keep any logs of the error msg.
One very strange route I could try is to reinstall notrack and than try to run the unistall script.

**Comment by quidsup** [comment]
/etc/cron.d/ntrk-parse

It is in the uninstall script, so Im not sure why it remained on your system?

**Comment by blub4747** [comment]
Thx for that additional information.

Unfornately my Debian 9 server upgraded from 8.
Has currently some problems to come online.
I have to see in the next couple of days how bad it is.
As for the  uninstall script I downloaded it to my home/Downloads folder and tried to run it with out success. Since that did not work I decided to unistall the components manually as I described above.
