### ISSUE TITLE
URL correction to admin/include/config-functions.php

### ISSUE THREAD

**Issue by Hexxium** [quidsup/notrack#237]
Current is
 `draw_blocklist_row('bl_hexxium', 'Hexxium Creations Malware List', 'Hexxium Creations are a small independent team running a community based malware database <a href="https://hexxiumcreations.com/domain-ip-threat-database/" target="_blank"><img class="btn" alt="Link" src="./svg/icon_home.svg"></a>');
`
We've moved things around alot since back when this was first added and "https://hexxiumcreations.com/domain-ip-threat-database/" results in a 404 now, I would recommend replacing it with "https://www.hexxiumcreations.com/projects/malicious-domain-blocking/" or "https://www.hexxiumcreations.com/report-malicious-domains-and-ips/"

Also, we simply call it "Hexxium Creations Threat List" now as it contains scam domains, phishing domains, and malware (etc) - essentially anything at all malicious

**Comment by quidsup** [comment]
Updated, thanks
