### ISSUE TITLE
NaN% allowed/blocked dns queries

### ISSUE THREAD

**Issue by Mattze96** [quidsup/notrack#239]
There is a by zero division in the svg code in index.php when the live table is empty.

Is the intendet behaviour to display 0 or "no queries made"? I may create a pull request then.

**Comment by quidsup** [comment]
I guess its rare to see zero, but yes this issue does need fixing

**Comment by quidsup** [comment]
Fixed in e73183907975fb29077e0c541a5a6257f67bf14d
