### ISSUE TITLE
Local ip blocked?

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#24]
Fresh install of notrack on my new HDD, seems the router website is blocked? maybe im missing something but it doesn't appear to be breaking anything 
http://prntscr.com/aajjd1

**Comment by quidsup** [comment]
I've been unable to replicate with my setup, but its been reported before.
I suspect the browser is trying to treat the IP address as URL and wants it resolved by the DNS server. But its not a resolvable address and ends up being denied (blocked)

I have amended the Stats page to show the difference between a blocked site vs an unresolvable site.
