### ISSUE TITLE
Why does NoTrack block the root directory of its server?

### ISSUE THREAD

**Issue by nothaddock** [quidsup/notrack#241]
I have my NoTrack server running on a Raspberry Pi 2, and I have it running with the name "dns.svc" for ease of access.

My question is, why does NoTrack block the root directory? I have an index.html in there, and I can't access it, even through the local IP. It sinkholes it (blank page) instead of giving me the index.html.

I found this entry in the Sites Blocked tab:
![NoTrack blocking my request in the "Sites Blocked" tab](https://user-images.githubusercontent.com/18602417/31863741-5ab9ed30-b728-11e7-9743-97b9cc7823dc.png)

**Comment by Mattze96** [comment]
Did you adjust `/etc/lighttpd/lighttpd.conf` ???
All requests that are not starting with /admin/*  are redirected into the sink-hole.
Keep in mind that if you use a generic filepath for your additional files this file is requested every time an advertisement points to it.

```
#If you want to add new web folders under /var/html/www then you need to modify the regex below.
#e.g $HTTP["url"] =~ "^(?!\/(admin|foo|bar))\/.*" {
$HTTP["url"] =~ "^(?!\/admin)\/.*" {
        # Create a response header for debugging using curl -I
        setenv.add-response-header = ( "X-NoTrack" => "Sod off trackers." )

        # Set the cache to 1 day for better performance
        expire.url = ("" => "access plus 1 days")

        # Send the query to sink.html
        url.rewrite = (".*" => "sink/index.html" )
}
```

**Comment by nothaddock** [comment]
> Did you adjust `/etc/lighttpd/lighttpd.conf` ???

No, I didn't. But, I will now.

I was just more or less wondering. But thanks anyway!
Also, this should be something highlighted in the wiki.
