### ISSUE TITLE
Valid hostname being blocked - sumologic.com

### ISSUE THREAD

**Issue by bgoleno** [quidsup/notrack#245]
Hi there, 

This is Brian from Sumo Logic.  Sumo Logic is a legitimate, and trustable site that is not used for user tracking. We do have customers that use our cloud based service for monitoring and troubleshooting of their web based applications. On of our clients is a very reputable developer of a browser plugin that does grammar validation. They use our service for monitoring and troubleshooting their distributed application.  This ad blocking plugin is blocking their access to our log collection endpoint, and preventing them from being able to support their application and their customers.  

Could you kindly remove our domain from your list, or whitelist us.

**Comment by quidsup** [comment]
Blocklists are no longer on this project
