### ISSUE TITLE
NoTrack with php7.1

### ISSUE THREAD

**Issue by akha666** [quidsup/notrack#246]
Hello
Is NoTrack work with php7.1?
I can't install it on Ubuntu 17.10 which is provided php7.1.

> Installing Lighttpd and PHP
> Reading package lists... Done
> Building dependency tree        
> Reading state information... Done
> E: Unable to locate package php7.0-cgi
> E: Couldn't find any package by glob 'php7.0-cgi'
> E: Couldn't find any package by regex 'php7.0-cgi'
> E: Unable to locate package php7.0-curl
> E: Couldn't find any package by glob 'php7.0-curl'
> E: Couldn't find any package by regex 'php7.0-curl'
> E: Unable to locate package php7.0-mysql
> E: Couldn't find any package by glob 'php7.0-mysql'
> E: Couldn't find any package by regex 'php7.0-mysql'

Thanks in advance.

**Comment by quidsup** [comment]
Untested, but hopefully it will work
