### ISSUE TITLE
Password for Admin settings

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#25]
I have port 80 port forwarded to i can access my Development Website and Multicraft away from home, but found out my friend can go to and change the /admin settings... not a good thing, i temporarily un-port forwarded but is there a way you can put some sort of password or something on the web ui?

**Comment by quidsup** [comment]
Fair one, I'll add that feature.

I hope you haven't got port 53 (DNS) accessible from outside? It can be abused and used in a DNS amplification attack, which was used against Github a couple of years ago.

**Comment by quidsup** [comment]
Work is now in progress, and will be completed in v0.7.8
