### ISSUE TITLE
[Info] Referencement

### ISSUE THREAD

**Issue by funilrys** [quidsup/notrack#255]
Hello @quidsup ,

Because I want to be transparent, I just wanted to inform you that we added `malicious-sites.txt` and `trackers.txt` to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/quidsup_malicious-sites](https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites) and [Ultimate-Hosts-Blacklist/quidsup_notrack_trackers](https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers) .

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by quidsup** [comment]
Hi @funilrys 
I don't know if you are aware, but I have moved the blocklists to a different repository on Gitlab https://gitlab.com/quidsup/notrack-blocklists

**Comment by funilrys** [comment]
Hi @quidsup,
We were informed by @dnmTX through Ultimate-Hosts-Blacklist/dev-center#7.

It's now updated in our templates and sources.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@quidsup  i got you man 😎

**Comment by funilrys** [comment]
@dnmTX Please report to https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites. https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers and https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/templates/README_template.md.



Closing as this is not going anywhere.
