### ISSUE TITLE
Windows version, come on!

### ISSUE THREAD

**Issue by christophered** [quidsup/notrack#258]
@quidsup thanks for your hard work man, but will you consider releasing a Windows version?

**Comment by ShayBox** [comment]
You could install it on WSL, i've gotten that to work, but you will have to use a VBS file to start WSL and hide the cmd prompt at windows startup

**Comment by christophered** [comment]
@ShayBox Tutorial?

**Comment by Serkan-devel** [comment]
Quite ironic, running notrack on a system that tracks

**Comment by christophered** [comment]
Windows 8 my dear not 10

**Comment by christophered** [comment]
@quidsup @ShayBox [Verigio Dns Firewall](https://www.verigio.com/products/dns-firewall/) works on Windows perfectly! I have found it, and now I can convert the notrack list to Verigio Dns Firewall xml list using Excel.

**Comment by kingdevnl** [comment]
Well you could aswell make a Virtual machine in virtualbox with network mode Bridge to run it
