### ISSUE TITLE
DNS Over TLS Support

### ISSUE THREAD

**Issue by oscartbeaumont** [quidsup/notrack#259]
Have You Considered Adding Support For DNS Over TLS With Notrack. It Would Allow The Upstream DNS Traffic To Be Encrypted Hiding The Traffic From An ISP. It Might Be Difficult To Implement As Dnsmasq Does Not Have Support For It But It Would Increase The Privacy Of The DNS Requests Being Made To The Upstream Providers.

**Comment by cbuijs** [comment]
Install getdns Stubby on same system as DNSMasq and have DNSMasq forward to it.

https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby
