### ISSUE TITLE
g.alicdn.com should not be blocked

### ISSUE THREAD

**Issue by Skaronator** [quidsup/notrack#263]
Not sure if I should report this but `g.alicdn.com` is required to load https://track.aliexpress.com/logisticsdetail.htm?tradeId=xxxx correctly. It act as CDN for CSS and JS files.

https://g.alicdn.com/cn/ae-physical-detail/2.0.0/styles/main.css
https://g.alicdn.com/cn/ae-physical-detail/2.0.0/scripts/main.js

**Comment by quidsup** [comment]
Removed in 335a076b9e757b3c0bca9953608855e8b5044ad7

**Comment by quidsup** [comment]
Sorry removed it now
