### ISSUE TITLE
Why is Ghostery.com blocked?

### ISSUE THREAD

**Issue by timmyrs** [quidsup/notrack#264]
AFAIK it's not a tracker.

**Comment by Serkan-devel** [comment]
Ghostery is known spyware and shouldn't be installed. Use something like ublock origin instead. It's open source even

**Comment by timmyrs** [comment]
I don't use Ghostery, but it's news to me that it's spyware. Do you have any sources on that?

**Comment by Serkan-devel** [comment]
This https://www.youtube.com/watch?v=_8FPbkq0O5s at 2:05 but it's in german

**Comment by timmyrs** [comment]
Thanks, I actually do speak German.
