### ISSUE TITLE
Ubuntu 18.04 lts and dnsmasq

### ISSUE THREAD

**Issue by briank8525** [quidsup/notrack#265]
Installed notrack on May 30th 2018.  In Ubuntu server 18.04 lts dnsmasq refused to start after installing notrack.   Ubuntu 18.04 lts bionic beaver server. kernel 4.15.0-22 generic.

dnsmasq refused to start - error was could not find network interface.
In this verison of server  netplan replaced ifupdown package. 
I fixed with the following.
apt-get install ifupdown.
/etc/network - wrote the interfaces file.  see below
# ifupdown has been replaced by netplan(5) on this system.  See
# /etc/netplan for current configuration.
# To re-enable ifupdown on this system, you can run:
#    sudo apt install ifupdown
auto enp2s0
iface enp2s0 inet dhcp

The last two lines of the files is what I added.  I then performed the following command.
systemctl restart dnsmasq.
problem resolved.  Notrack works normally

**Comment by quidsup** [comment]
Fixed now
