### ISSUE TITLE
[request] issue a "release" when hosts files are updated

### ISSUE THREAD

**Issue by dnmTX** [quidsup/notrack#267]
Hi there.As the title says is it possible to issue a "release" when you do updates on your hosts files?
Like the one you have here: https://github.com/quidsup/notrack/releases
Other repos doing it and it's easier this way to keep track on feature updates instead of checking here every day or so.
Thank you for considering it. 🙂 👍

**Comment by quidsup** [comment]
I've split the block list files from this project and moved them to GitLab
I know it says daily at the moment, but I haven't managed to fully automate the update script. Realistically it will be more like one or two updates per week.
https://gitlab.com/quidsup/notrack-blocklists/

**Comment by dnmTX** [comment]
Thanks @quidsup,i'll get them from there.
Closing.....
