### ISSUE TITLE
Notrack blocking itself

### ISSUE THREAD

**Issue by KonstaX** [quidsup/notrack#270]
![image](https://user-images.githubusercontent.com/18502553/44005053-1c8493f8-9e6d-11e8-9cff-6668a4ea8678.png)

I am not sure why this happened. Since I was running it in a VM i reversed it to a snapshot.

**Comment by duramato** [comment]
Thats expected behaviour, if you want to access the web UI, you need to access `/admin`, meaning in your case it is: `192.168.1.38/admin`

**Comment by KonstaX** [comment]
O yes, I forgot about that.

**Comment by Serkan-devel** [comment]
![trust-nobody-not-even-yourself-credits-to-bakoahmed-and-watermelonhero_fb_4373367](https://user-images.githubusercontent.com/16866642/44005297-99025574-9e71-11e8-8209-63540f6f22f2.jpg)

**Comment by quidsup** [comment]
Fixed in NoTrack v0.9
