### ISSUE TITLE
What's going on....?!?

### ISSUE THREAD

**Issue by angelos-alexiou** [quidsup/notrack#274]
Can someone please explain me what's going on? And all these are still happening for more that two weeks...
![1](https://user-images.githubusercontent.com/23134506/46630071-b685ae00-cb4b-11e8-85b2-0eb477976008.png)

Sorry for posting these images here, but I'm not aware how to get support / information regarding my next actions.

My system is:
- D/O droplet
- Ubuntu 18.04 LTS
- NoTrack v0.8.10

What actions I need to take for all these?

Thanks.

**Comment by quidsup** [comment]
Is that IP address 164.215.2.190 yours?
No - Your NoTrack device is open up to the world. Change the Firewall settings to restrict access to your IP / IP ranges that you use

Yes - Likely a false positive.
Establish which blocklist is preventing access to digicert.com
On that Admin page: Config > View Sites Blocked, then do a search for digicert.
It will tell you the blocklist which is preventing access to digicert.
Either disable the blocklist, or whitelist digicert
