### ISSUE TITLE
Admin page dont load propertly after clean debian instalation

### ISSUE THREAD

**Issue by regrepl** [quidsup/notrack#275]
I've done clean install of current Linux Debian on physical machine.
4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

Use the script for installation and everything went fine according to log, but the effect was a not working version of admin panel.

I'm getting something like this.
![2019-02-27 16-15-40](https://user-images.githubusercontent.com/39137187/53500691-21a83080-3aab-11e9-8596-54046457d8fd.png)

From what can I tell Lighttpd don't start
`● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-02-27 16:09:49 CET; 6s ago
  Process: 21895 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255)
  Process: 21887 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 21895 (code=exited, status=255)

lut 27 16:09:49 PC-XXX systemd[1]: lighttpd.service: Failed with result 'exit-code'.
lut 27 16:09:49 PC-XXX systemd[1]: lighttpd.service: Service hold-off time over, scheduling restart.
lut 27 16:09:49 PC-XXX systemd[1]: Stopped Lighttpd Daemon.
lut 27 16:09:49 PC-XXX systemd[1]: lighttpd.service: Start request repeated too quickly.
lut 27 16:09:49 PC-XXX systemd[1]: Failed to start Lighttpd Daemon.
lut 27 16:09:49 PC-XXX systemd[1]: lighttpd.service: Unit entered failed state.
lut 27 16:09:49 PC-XXX systemd[1]: lighttpd.service: Failed with result 'exit-code'.`
I'm attaching install log

[Install.log](https://github.com/quidsup/notrack/files/2910917/Install.log)

**Comment by simokarpin** [comment]
Seems to miss out from install script:
lighttpd-enable-mod fastcgi-php

**Comment by quidsup** [comment]
I've tested the new version of NoTrack 0.9 with Debian Testing and correctly configures Lighttpd now

**Comment by quidsup** [comment]
Fixed in e73183907975fb29077e0c541a5a6257f67bf14d
