### ISSUE TITLE
notrack blocks /phpmyadmin on same server

### ISSUE THREAD

**Issue by satscape** [quidsup/notrack#297]
I have phpmyadmin on the same server as notrack and it's blocking access to it and it seems any non-notrack file on my server, how do I fix that?

**Comment by simokarpin** [comment]
You should add this to "/etc/nginx/sites-available/nginx.conf" file.
`location ~ ^/phpmyadmin/(.+\.php)$ {
                   try_files $uri =404;
                   root /usr/share/;
                   fastcgi_pass unix:/run/php/php7.2-fpm.sock;
                   fastcgi_index index.php;
                   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                   include /etc/nginx/fastcgi_params;
           }
           location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
                   root /usr/share/;
           }`
