### ISSUE TITLE
Misc questions

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#30]
Hey, 

- Is there a way i can route dns requests of the server NoTrack is on to notrack itself?
- Is there any i can make all new devices connected to the network to use NoTrack dns ?
- Could you add an option to add AdBlockPlus/ublock lists?
- Could you also add a way to block a domain from within the Domain Stats page?
- And atlast an option to costumize the block message

**Comment by quidsup** [comment]
1. Yes, set DNS IP to 127.0.0.1 in /etc/network/interfaces
2. Yes, enable DHCP. A link to a tutorial video is provided.
3. ABP EasyList and Easy Privacy are available, as well as quite a few of the lists uBlock uses. I'm looking at adding more in the future.
4. That feature was added today
5. You can switch between 1pixel gif and message "Blocked by NoTrack" via the Admin page. If you want to customise it further you can change /var/www/html/sink/index.html
(It could be a security risk if I allow custom options in the Admin page)

**Comment by duramato** [comment]
Regarding the custom lists, it would be better if it was an option for the user as i can want to put my own private lists or just misc ones. Always better than beeing stuck to the ones that come from origin.
Ive found that if i disable a domain from the Blocking list it doesnt disable it. And if i try to disable the NoTrack or the TLD list i cant, and if i try to refresh the page they will be on again. This doesnt happen with any of the others

As a side note, do you have any  irc channel? either for this project or a personal one, i like always like to ask simple questions there rather than opening issues on github

**Comment by quidsup** [comment]
I just came across that issue today with Blocklists not saving. Its sorted now, the issue got introduced when I added the pause feature.

You can put your own block lists into /etc/dnsmasq.d folder. As long as they're formatted correctly the DNS server will use them. 

I don't have my own irc channel, but I'm pretty active on the South Wales LUG, details of their irc channel can be found here: http://swlug.org.uk/
