### ISSUE TITLE
Unresolved v21.03, ntrkupgrade.py, line 324, ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by githubuser181226** [quidsup/notrack#305]
Hi. I'm getting this error while trying to upgrade manually. 

Current setup 20.12, Ubuntu Server 18.04.5 LTS / 4.15.0-140-generic

```
notrack@notrack-ubuntu:~/notrack/src$ sudo python3 ntrkupgrade.py

NoTrack Upgrader
2021-03-30 00:14:05 WARNING __main__     Temporary copy of NoTrack block list is not available, I don't know what the latest version of NoTrack is :-(
2021-03-30 00:14:05 WARNING __main__     Either the file is missing due to a system reboot, or NoTrack block list is not enabled
Traceback (most recent call last):
  File "ntrkupgrade.py", line 378, in <module>
    main()
  File "ntrkupgrade.py", line 369, in main
    ntrkupgrade.is_upgrade_available()
  File "ntrkupgrade.py", line 324, in is_upgrade_available
    intlatest = int(self.__latestversion.replace('.', ''))
ValueError: invalid literal for int() with base 10: ''

```

Please, advise.

**Comment by quidsup** [comment]
Thanks for reporting this error, it relates to the formatting in the temporary download of /tmp/bl_notrack.txt having an extra space on the line `# LatestVersion`

Options are either:
- Manually edit the file to remove the space between # and LatestVersion
- Wait up to 4 days for the file to be replaced with what is now a correctly formatted version
- `git pull` to replace the existing python script, which provides a compatible regular expression

Rerun `sudo python3 ntrkupgrade.py` once one of the above has been done

**Comment by githubuser181226** [comment]
I have no /tmp/bl_notrack.txt on my system.
So, I ran 
`wget https://github.com/quidsup/notrack/raw/master/install-ubuntu.sh`
again today, but still got version 20.12 (same link to gitlab also downloads 20.12)
I ran it anyway to create temp files, checked /tmp/bl_notrack.txt and it didn't have the space, no errors, then ran ntrkupgrade.py and also no errors this time.
dashboard still says version 20.12. is version 21.03 ready yet?
Cheers.

**Comment by githubuser181226** [comment]
Hi.
Thanks for the response.
> Thanks for reporting this error, it relates to the formatting in the temporary download of /tmp/bl_notrack.txt having an extra space on the line `# LatestVersion`
> Options are either:
>     * Manually edit the file to remove the space between # and LatestVersion

I would do that, but I don't have that file on my system. 

>     * Wait up to 4 days for the file to be replaced with what is now a correctly formatted version
>     * `git pull` to replace the existing python script, which provides a compatible regular expression

I don't know how to do that, so I think I'll wait for the release of 21.03.
Cheers.

**Comment by githubuser181226** [comment]
Hi.
I'm reopening and renaming, because even after a clean install of 21.03 `ntrkupgrade.py` script errors out exactly like in OP.

If an upgrade is not possible, please consider:
- changing the instructions to recommend a clean install
- tell us how to do a proper re-install (simply re-running install bash script doesn't work).

Cheers.
