### ISSUE TITLE
Web server save changes bug

### ISSUE THREAD

**Issue by mcfrojd** [quidsup/notrack#32]
I found out a bug when you press "save changes" on the "config / general" "web server" settings.
Somehow the graphics become duplicated.
![skarmklipp 2016-03-09 11 10 13](https://cloud.githubusercontent.com/assets/7395495/13632204/d28395ea-e5e8-11e5-8bbe-2ee9e8be324a.png)

**Comment by quidsup** [comment]
Thanks, I've been making some changes to config, and hadn't finished this bit off.
