### ISSUE TITLE
Public DNS Server?

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#35]
So, i though of an idea, you buy a server, that has capable network and everything, set it up as a dns server and install notrack, then let the community use it, and have a donation page or maybe a monthly fee to use it, and if someone doesn't want to pay or use the specific settings the dns is using, they can always install it on there own server, i'd donate for that. i'd be a cool idea, you'd just have to make sure you can get enough donations or subscriptions for it

**Comment by quidsup** [comment]
I would have to think very carefully about how to implement a public dns server, sadly they are very easy to abuse.

**Comment by ShayBox** [comment]
Yea, that would probably get attacked alot

**Comment by mattpalermo** [comment]
What types of attacks would have to be considered? I am aware that an open recursive dns is vunerable to a [DNS amplification attack](https://www.digitalocean.com/community/questions/abuse-complaint-about-dns-server). I was considering trying out rate limiting to prevent this. Would that be a suitable solution? Is there any other types of attacks to consider?

I am considering playing around with a public no track service.

**Comment by dschaper** [comment]
http://www.openresolverproject.org/

**Comment by mattpalermo** [comment]
@dschaper thanks. It seems that this service won't check my DNS straight away. http://www.openresolverproject.org/search2.cgi?botnet=yessir&search_for=103.16.128.210

**Comment by mattpalermo** [comment]
Here is my attempt to go head first into this topic: https://github.com/mattpalermo/Public-No-Track-Service. Any feedback is welcome.

**Comment by ShayBox** [comment]
Nice job!

**Comment by quidsup** [comment]
Very nice. Do you mind if I mention that in Google+ and Twitter? Maybe we can see how it handles some real world traffic?

**Comment by duramato** [comment]
From my personal experience, if you have a dnsmasq server open to the public it can be very easily abused, for DDOS, trolling ex: https://gist.github.com/duramato/44d92c4840dae44d5318b9ac9e237e3f and such malicius intents. You must have something like fail2ban for automated blocking.

**Comment by mattpalermo** [comment]
@quidsup yes please. I'm interested to see how it holds up and perhaps get some user feedback.

@duramato I haven't made the dnsmasq server public, but instead proxy requests through a BIND9 server. I do this so I can use the BIND9 RRL feature to prevent amplification attack. I haven't considered DDoS. I'll check out fail2ban, thanks for the pointer :)

**Comment by mattpalermo** [comment]
@duramato I don't quite understand what your gist demonstrates. Could you explain some more?

**Comment by duramato** [comment]
Basically that's a snippet from my dnsmasq, which was beeing abused just for "Trolling" i guess, and as a consequence was bringging my dnsmasq to it's knees. A sort of explanation i found just now, with a quick google, about that "enlansg . com", https://www.reddit.com/r/pihole/comments/5ogyg1/log_file_finding_odd_political_things_in_the_log/

**Comment by mattpalermo** [comment]
Hmm... I'll look out for that one. That PiHole project is interesting. From the surface it seems to overlap in functionality with notrack a little bit (but that's getting off topic now).
