### ISSUE TITLE
NoTrack on a VPS

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#39]
When installing on a vps notrack doesnt work, since the network interfaces have both a local and the public ip, Creating the lists wrong
```
service dnsmasq start
 * Starting DNS forwarder and DHCP server dnsmasq
dnsmasq: bad option at line 2 of /etc/dnsmasq.d/easylist.list
                                                                         [fail]
```
Ifconfig:
```
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:158 errors:0 dropped:0 overruns:0 frame:0
          TX packets:158 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:21175 (21.1 KB)  TX bytes:21175 (21.1 KB)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00                                                                                                                                                              -00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.                                                                                                                                                              255
          inet6 addr: 2607:3f00:11:38::f/128 Scope:Global
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:1033 errors:0 dropped:0 overruns:0 frame:0
          TX packets:777 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:102629 (102.6 KB)  TX bytes:407554 (407.5 KB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00                                                                                                                                                              -00
          inet addr:**PUBLICIP**     P-t-P:**PUBLICIP**      Bcast:**PUBLICIP**                                                                                                                                                          Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

Small example from **easylist.list** :
```
address=/007-gateway.com/127.0.0.2
**PUBLICIP**        
address=/0icep80f.com/127.0.0.2
**PUBLICIP**
address=/101m3.com/127.0.0.2
**PUBLICIP**
address=/103092804.com/127.0.0.2
**PUBLICIP**
address=/10fbb07a4b0.se/127.0.0.2
**PUBLICIP**
address=/10pipsaffiliates.com/127.0.0.2
**PUBLICIP**
```

The Public Ip should not be there, removing it fixes it

**Comment by quidsup** [comment]
Can you run notrack.sh manually and paste the first few lines here please
e.g.
$ sudo notrack -f
Reading Config File
IP Version: IPv4
Reading IPv4 Address from eth0
System IP Address 192.168.62.3

**Comment by duramato** [comment]
```
Reading Config File
IP Version: IPv4
Reading IPv4 Address from venet0
System IP Address 127.0.0.2
PUBLICIP
```

**Comment by quidsup** [comment]
I've had a couple of ideas on how to fix the issue:
1. Make sure only a single line is taken from "ip addr"
2. Pattern match with regex

I'm trying the easy option 1. and have edited function "Get_IPAddress()"

$ sudo ntrk-upgrade
or /admin/upgrade.php?u=1

**Comment by duramato** [comment]
```
sudo ntrk-upgrade
Error Unable to find NoTrack folder
Aborting
``` 
Could it be that i installed as the root user? I used the default option ,the one that is not /opt iir

**Comment by quidsup** [comment]
Where did the notrack folder end up?

**Comment by duramato** [comment]
Tbh i dont know 
`find / -name NoTrack -type d` NoTrack is the folder name right?

**Comment by quidsup** [comment]
It will either be called "notrack" or "NoTrack"
Default is to install under the home folder of user running the install.sh, or the sudo user if root user ran the installer

**Comment by duramato** [comment]
```
find / -name notrack -type d
/notrack
/etc/notrack
/var/log/notrack
```
 I guess it got put on the root partition becouse its run as root? But they / and not /root ?

**Comment by quidsup** [comment]
Ah that would be why it couldn't find it then, I'll fix the installer to prevent that happening

For now I guess it will work if you mv /notrack to your home folder

**Comment by quidsup** [comment]
Oops I hit the wrong button and accidentally closed the issue

**Comment by duramato** [comment]
Even if i put it on /root it doesnt detect it

**Comment by quidsup** [comment]
It should now, but you'll have to "git pull" the update first

**Comment by duramato** [comment]
Still not working

```
ntrk-upgrade
Error Unable to find NoTrack folder
Aborting
```

```
 git rev-parse HEAD
7868f96c19bacdd53f393dd85769b0fd14214f12
```

**Comment by duramato** [comment]
It is still creating the .list files wrong like on the OP, about the install not being detected ive switch to /opt instead.

**Comment by duramato** [comment]
The ip adress issue is still present, its really driving me nuts as i can't run NoTrack

```
# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: 2607:3f00:11:500::f/128 Scope:Global
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:270 errors:0 dropped:0 overruns:0 frame:0
          TX packets:297 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:33611 (33.6 KB)  TX bytes:56950 (56.9 KB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:IPADRESS  P-t-P:IPADRESS  Bcast:IPADRESS  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

Isn't it possible to: When more than on ip adress is presented for a card to choose between both or something along those lines

**Comment by quidsup** [comment]
I spotted a mistake in the code to get the IP address.
Let me know what happens now

**Comment by duramato** [comment]
Seems to be working , took a quick look at notrack.list 
snippet:
```
address=/1-creative-1.com/127.0.0.2
address=/103bees.com/127.0.0.2
address=/10cms.com/127.0.0.2
address=/123count.com/127.0.0.2
```

As for install i used the /opt option and not the user directory, so i don't know if its still an issue that issue

**Comment by duramato** [comment]
Mmm somethings funky now
Take a note at the DNS Queries, and at the 3 domains and each with 1 request.
![image](https://cloud.githubusercontent.com/assets/10121067/16710742/a6c51416-4631-11e6-9005-a108e4e25bf1.png)

![image](https://cloud.githubusercontent.com/assets/10121067/16710740/9f38092e-4631-11e6-8f1b-aecc756eb295.png)

**Comment by duramato** [comment]
The sites blocked page only shows a count of 5 , which where from when acessed the http web server, from for example direct ip on a browser. And all show the adress blocked as the server's public IP
![image](https://cloud.githubusercontent.com/assets/10121067/16710771/a9b11bd8-4632-11e6-94f8-299a5127ffd0.png)

**Comment by duramato** [comment]
Also going to any of the blocked pages, ex `google-analytics.com` i just get a `ERR_CONNECTION_REFUSED` error message instead of the "warm and welcoming" , blocked by NoTrack (which is what i have set up)

**Comment by quidsup** [comment]
You need to set a LAN facing network card to respond to DNS queries, is that your vnet0:0 device?
Change it in /etc/notrack/notrack.conf
Then run sudo notrack -f

Mine responds with 192.168.x.y with the blocked DNS queries, which allows any browser on my LAN to connect back to notrack

Yes there is caching on the DNS Queries page. The longer the timescale you're looking at, the longer the caching.
After a busy day of activity it comes in quite handy

**Comment by duramato** [comment]
I tried changing vnet0:0 and:
```
~# sudo notrack -f
Reading Config File
IP Version: IPv4
Reading IPv4 Address from venet0:0
System IP Address 127.0.0.2
```
same thing maybe becouse it seems venet0:0 is a sub card from the venet0? I think for it to work it would need to respond with the VPS's public ip, since im not in its LAN. But when i was running notrack at home i think it worked when acessing from outside my network, altought im not sure.

One more thing i noticed is that when acessing `HOST/admin/config.php?v=sites`  i just get a 500 response code, taking a look at lighttpd logs i see ```2016-07-10 09:24:53: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4800010 bytes) in /opt/notrack/admin/config.php on line 292```

**Comment by quidsup** [comment]
Im splitting those out as two new issues

**Comment by duramato** [comment]
I just tried running `sudo ntrk-upgrade` and then `sudo notrack -f` the  chneasy seems to be fixed, but this's issue issue with the ip is the same. It still responds on the DNS queries with  `127.0.0.2`

```
Jul 10 18:39:06 dnsmasq[19115]: query[A] www.google.com from IP
Jul 10 18:39:06 dnsmasq[19115]: forwarded www.google.com to 8.8.8.8
Jul 10 18:39:06 dnsmasq[19115]: reply www.google.com is 216.58.208.228
Jul 10 18:39:13 dnsmasq[19115]: query[A] googleadservices.com from IP
Jul 10 18:39:13 dnsmasq[19115]: config googleadservices.com is 127.0.0.2
Jul 10 18:39:13 dnsmasq[19115]: query[A] googleadservices.com from IP
Jul 10 18:39:13 dnsmasq[19115]: config googleadservices.com is 127.0.0.2
```
resulting in the `ERR_CONNECTION_REFUSED` still

**Comment by quidsup** [comment]
I only had about 15 mins spare last night, and had just enough time to temporarily fix was the China blocklist

You can now set a custom IP for notrack. Its not the most user friendly, but it was the easiest option to code.

In /etc/notrack/notrack.conf
`IPVersion = 192.168.x.y`

Check with `notrack --test`

IPVersion is effectively over-ridden, so you can set a custom IPv4 or IPv6 address.
config.php also shows when you're using a custom IP.

**Comment by duramato** [comment]
Ok it seems to be working now! Thanks
I did had to run `sudo notrack -f` besides the upgrade cmd (I think probably to regenerate the lists with the correct adress) . 
A thing i noticed was after running `sudo notrack -f` the `Block Message:` got reset to the 1x1 blank pixel (i had it on the message option), the ui still showed it as beeing ticked on the `Message - Blocked by NoTrack` but i had to thick the pixel and back again the `Message - Blocked by NoTrack` for it to work again.

Another thing i saw was if i was using `IPVersion = IPv4` or with an ip adreess `IPVersion = 192.168.x.y` it always showed as 
```
Internet Protocol:	IPv4
IP Address:	ADRESS
```
on the config.php page , regardless of the option it was on.

One side question, do you have any "schedule" to check the reports for the NoTrack list , or is just when you have the time/feel like doing it. And would you want help with it? :P ( Its this file that would need updating right? https://github.com/quidsup/notrack/blob/master/trackers.txt )

**Comment by quidsup** [comment]
The config file is cached for about 10mins or so.

I certainly would appreciate some help with the trackers.txt file. It's a huge game of whack-a-mole, I don't have any particular schedule for updates.
I have notrack throttled to only check for updates every two days (unless you override it with -f / --force)
