### ISSUE TITLE
Adding/allowing other search engines than google for domain search

### ISSUE THREAD

**Issue by deriv** [quidsup/notrack#41]
While google is certainly a rather good search engine, it also is the very manifestation of everything that notrack tries to prevent and avoid. Therefore it would be only reasonable to add user an option to use alternative search engines, such as:

Startpage, https://startpage.com
- Google search with privacy.

or Ixquick , https://ixquick.eu

- Combines the top ten results from multiple search engines. It does not store users' personal details or IP addresses and it uses SSL. Also provides an international phone directory. 

which do not collect data.

Or to allow user define own search engine.

Related: https://prism-break.org/en/all/#web-search

**Comment by quidsup** [comment]
I've added a few search engines.
In regards to Startpage / Ixquick, I can't work out how to parse a search string to them.

**Comment by deriv** [comment]
StartPage: https://startpage.com/do/search?q=%s
Ixquick: https://ixquick.eu/do/search?q=%s

I've never used GitHub before, but I believe I've managed to implement those two and request merging.

**Comment by quidsup** [comment]
Thanks. It does take a bit of getting used to with Git.
I've added StartPage and Ixquick to config.php $SearchEngineList, making them selectable
