### ISSUE TITLE
Error installing on arch linux

### ISSUE THREAD

**Issue by Serkan-devel** [quidsup/notrack#42]
This is the output I get when I run this on Arch Linux running on a Raspberry Pi 2 model B: http://paste.ubuntu.com/16733201/

**Comment by quidsup** [comment]
I guess Arch doesn't have whiptail pre-installed?
https://www.archlinux.org/packages/community/i686/libnewt/files/

I've been thinking about removing the fancy whiptail based menus from the Installer to facilitate installation of NoTrack onto FreeBSD

**Comment by duramato** [comment]
Light ubuntu installs also don't come with it, VPSs i.e. , you could perhaps if whiptail isn't found provide another way without requiring it, even tho it's standart in many OSs

**Comment by quidsup** [comment]
I've written a custom menu function.
I had some vague recollection of something I wrote half a lifetime ago in QBasic.
Choices are parsed as arguments into the function
You can use either a numeric key, or up down arrow keys

Menu() {
  local Choice
  local Highlight
  local MenuSize  
  local Valid;
  
  Highlight=1
  MenuSize=0
  clear
  while true; do    
    for i in "$@"; do
      if [ $MenuSize == 0 ]; then                #$1 Is Title
        echo $1
        echo
      else        
        if [ $Highlight == $MenuSize ]; then
          echo " * $MenuSize: $i"
        else
          echo "   $MenuSize: $i"
        fi
      fi
      ((MenuSize++))
    done
        
    read -r -sn1 Choice;
    echo "$Choice"
    if [[ $Choice =~ ^[0-9]+$ ]]; then
      if [[ $Choice -ge 1 ]] && [[ $Choice -lt $MenuSize ]]; then
        return $Choice
      fi
    elif [[ $Choice ==  "A" ]]; then             #Up
      if [ $Highlight -le 1 ]; then
        Highlight=$((MenuSize-1))
        echo
      else
        ((Highlight--))
      fi    
    elif [[ $Choice ==  "B" ]]; then             #Down
      if [ $Highlight -ge $((MenuSize-1)) ]; then 
        Highlight=1
        echo
      else
        ((Highlight++))
      fi   
    elif [[ $Choice == "" ]]; then
      return $Highlight
    fi  
    #C Right, D Left
    
    MenuSize=0
    clear   
  done
}
