### ISSUE TITLE
Error. Unable to detect IP Address

### ISSUE THREAD

**Issue by MCNotex** [quidsup/notrack#44]
> Select Menu Device
> 
>  \* 1: eth0
>    2: tun0
> 
> Select IP Version being used
> 
>  \* 1: IP Version 4 (default)
>    2: IP Version 6
> 
> IP Version: IPv4
> Reading IPv4 Address from 1
> Device "1" does not exist.
> Error. Unable to detect IP Address
> Aborting

For some reason it's trying to find a device called "1", not eth0.

**Comment by quidsup** [comment]
My mistake, I threw new menu code up late last night and hadn't tested it with multiple network devices.

**Comment by MCNotex** [comment]
Thank you for the fix, it's all working now :D
