### ISSUE TITLE
No redirect to Login page  - (user and password present in notrack.conf).

### ISSUE THREAD

**Issue by 4u4z** [quidsup/notrack#47]
Hi.

I think that the current version of Notrack (0.7.12) is not redirecting to the Login page  when it should. (user and password present in notrack.conf).

My notrack.conf file contains (with many other lines) the following.

```
...
Username = notrackadmin
Password = $2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a
...
```

So I expected to have the login page the next time I accessed the "https://my_server_ip/admin", but that is not the case.

I think this is related with the new "`function LoadConfigFile() { ...`" in the "<notrack_home>/admin/include/global-functions.php" file.

In that function we can find the following lines:

```
//Load Config File---------------------------------------------------
function LoadConfigFile() {
  ...
            case 'Password':
              $Config['Password'] = Filter_Str_Value($SplitLine[1], '');
              break;
  ...

```

In `function Filter_Str_Value($Str, $DefaltValue='') { ...`  we have:

```
//Filter String Value------------------------------------------------
function Filter_Str_Value($Str, $DefaltValue='') {
  //1. Check String Length is > 0 AND String doesn't contain !"£$%^&()+=<>,|/\
  //2. Return Str on success, and Default on fail
  
  if (preg_match('/[!\"£\$%\^&\(\)+=<>:\,\|\/\\\\]/', $Str) == 0) {
    return $Str;
  }  
  return $DefaltValue;
}
```

The function above will always return an empty string (the default),. The reason is that the password hashes produced by PHP "password_hash" function WILL contain "$" chars.

Then a empty "password" will be stored in the `$Config['Password'] `, this will have the same effect of NOT having a password configured in the first place.

I have made a simple but extremely "ugly" solution, that works for me and for now (until someone with more skill makes a good fix).

I have never used GitHub, so I'm not even sure how I could share that solution with everyone else.

**Comment by quidsup** [comment]
Thanks, my over sensitive approch to security would have prevented a password from loading.
I've taken off the filter.

I'm away from home and can't test it right now, but its a simple change and should work ok.
