### ISSUE TITLE
create-ssl-cert.sh still uses whiptail

### ISSUE THREAD

**Issue by Serkan-devel** [quidsup/notrack#49]
Since I had troubles trying to install notrack on archlinux, I would encounter the same problem with creating an ssl-certificate with the pre-packed files. Probably there are more files still using whiptail.

**Comment by RyanBlue** [comment]
The uninstaller also still uses whiptail.

**Comment by quidsup** [comment]
I've sorted out create-ssl-cert script.
I'll start on the uninstaller later

**Comment by quidsup** [comment]
Fixed now
