### ISSUE TITLE
Google and PW

### ISSUE THREAD

**Issue by LucasRoot** [quidsup/notrack#5]
Why doesn't have any blacklisted site from Google?
The few that are blocklisted are commented.
And you should add pw domains to blocked sites.
I don't know any famous .pw site

**Comment by LucasRoot** [comment]
PS: These domains are trackers from Windows 10 and doesn't exist in the list of trackers.

aidps.atdmt.com
apps.skype.com
a.rad.msn.com
a.ads2.msads.net
aka-cdn-ns.adtech.de
b.rad.msn.com
b.ads2.msads.net
b.ads1.msn.com
bs.serving-sys.com
c.msn.com
cdn.atdmt.com
cds26.ams9.msecn.net
c.atdmt.com
db3aqu.atdmt.com
ec.atdmt.com
h2.msn.com
msntest.serving-sys.com
m.adnxs.com
m.hotmail.com
secure.flashtalking.com
static.2mdn.net
s.gateway.messenger.live.com
secure.adnxs.com
sO.2mdn.net
ui.skype.com
http://www.msftncsi.com
msftncsi.com
*.data.microsoft.com
*.telemetry.microsoft.com
wes.df.telemetry.microsoft.com
survey.watson.microsoft.com
corpext.msitadfs.glbdns2.microsoft.com
compatexchange.cloudapp.net
cs1.wpc.v0cdn.net
a-0001.a-msedge.net
*.update.microsoft.com.akadns.net
fe2.update.microsoft.com.akadns.net
*.support.microsoft.com
corp.sts.microsoft.com
pre.footprintpredict.com
i1.services.social.microsoft.com.nsatc.net
feedback.microsoft-hohm.com
ad.doubleclick.net
ads.msn.com
ads1.msads.net
a.ads1.msn.com
a.ads2.msn.com
adnexus.net
az361816.vo.msecnd.net
az512334.vo.msecnd.net
prod-w.nexus.live.com.akadns.net
view.atdmt.com
telecommand.telemetry.microsoft.com
telecommand.telemetry.microsoft.com.nsatc.net
oca.telemetry.microsoft.com
oca.telemetry.microsoft.com.nsatc.net
sqm.telemetry.microsoft.com
sqm.telemetry.microsoft.com.nsatc.net
watson.telemetry.microsoft.com
watson.telemetry.microsoft.com.nsatc.net
choice.microsoft.com.nsatc.net
df.telemetry.microsoft.com
reports.wes.df.telemetry.microsoft.com
services.wes.df.telemetry.microsoft.com
sqm.df.telemetry.microsoft.com
watson.ppe.telemetry.microsoft.com
telemetry.appex.bing.net
telemetry.appex.bing.net:443

**Comment by quidsup** [comment]
Thanks I'll add them to the list

I can't think I've seen anything much in the way of malicious sites from .pw domain

**Comment by quidsup** [comment]
msftncsi.com blocks updates in Windows 7.
For most of the sites I've opted to block the whole domain, e.g. atdmt.com is Facebook ads, so no reason to allow anything from that domain

**Comment by LucasRoot** [comment]
Alright.

Cheers!
