### ISSUE TITLE
Adding malware blocklist

### ISSUE THREAD

**Issue by Serkan-devel** [quidsup/notrack#50]
There is an independent team running a malware-domain database updated by people submitting malware domains and reviewed by the team at <a href="https://hexxiumcreations.com/domain-ip-threat-database/">https://hexxiumcreations.com/domain-ip-threat-database/</a>. One stated <a href="https://www.youtube.com/watch?v=WqKWNuLDAn0">here</a> that developers are working with this open database. It would fit perfectly with notrack which already blocks trackers by default. If malware too, that would be a killer feature.

**Comment by quidsup** [comment]
Thanks for the link. I've been watching the list over the past few days. It looks like they're doing a good job with it, I'll look into incorporating it into notrack

**Comment by duramato** [comment]
I did noticed that, that list also contains malware hosted on ok domains ex: `hxxp://www.mediafire.com/download/fcdc2fzzdg3/MALWARE_FILE.exe`

mediafire is a cloud hosting company, so blocking their domain wouldnt make sense, while other entries on the list make complete sense like `hxxps://downloadgenerators.com/`

**Comment by Serkan-devel** [comment]
![auswahl_038](https://cloud.githubusercontent.com/assets/16866642/16830519/d954b1c2-499f-11e6-8743-c3557bd713f2.png)

**Comment by quidsup** [comment]
Thanks, I've sent an email

**Comment by Serkan-devel** [comment]
![auswahl_043](https://cloud.githubusercontent.com/assets/16866642/17282997/0cee66b2-57ac-11e6-8fbe-c0814c646a1e.png)

**Comment by Serkan-devel** [comment]
http://discord.me/scammersublounge

**Comment by floogulinc** [comment]
I'm the main dev working on this list project right now. If you want to use the list in your program you can use the adblock plus formatted list hosted here: https://hexxiumcreations.github.io/threat-list/hexxiumthreatlist.txt

**Comment by quidsup** [comment]
Thanks floogulinc with the Adblock plus format I can drop it straight in

**Comment by quidsup** [comment]
Added as a default on list

**Comment by floogulinc** [comment]
Awesome, feel free to close this issue then.

**Comment by Serkan-devel** [comment]
YAY
