### ISSUE TITLE
Support for adding custom ADBlock compatible lists

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#55]
There are many out there on the internetz avaiable, many region specific and that cater to specific use cases. I myself have one with bad domains/sites i've been collecting.
Having the option to just input it's url and possibly a costum name ( like you can do on uBlock for example) would be a big advantage.

**Comment by quidsup** [comment]
This is a feature I would like to have.

There are several different forms of block list types, e.g. Easylist, DNS list, or a plain list. 
Either php or bash script needs to interpret what sort of list it is.

**Comment by quidsup** [comment]
Started work on this feature, so far NoTrack is able to identify ABP Easylists.

ToDo:
Input validation required on config.php > UpdateBlockListConfig()
Further interpretation options to be added to notrack.sh > Get_Custom()
Use GetFileTime() to ensure list is only processed every few days

**Comment by quidsup** [comment]
Feature is in final testing

**Comment by quidsup** [comment]
Feature added
