### ISSUE TITLE
Lateral discovery of Trackers

### ISSUE THREAD

**Issue by quidsup** [quidsup/notrack#63]
Many Tracking / Advertising companies utilise multiple domains and sub-domains as part of a defence against blocking. Some companies have a lot of them, in particular IBM Silverpop Systems which has over 7000 domains.

These are some of the sites I use to identify lateral domains:
[Whoisology](https://whoisology.com) is great for doing Reverse Whois lookups – finding other domains registered by each company. Downside is you have to register to get more information, and they restrict the amount of research you can do with free registration.

[Research Clinic](http://researchclinic.net/reverse-whois.html) is another Reverse Whois lookup, but the search isn’t that good. No Registration required.

[YouGetSignal](http://www.yougetsignal.com/tools/web-sites-on-web-server/) Reverse IP lookup. Tells you which sites are running on an IP. Sometimes useful, but no good when the server is shared between multiple companies.

[Robtex ](https://www.robtex.com/) Free to use, more complex than the other sites I’ve listed. 

Connected domains are indicated by the # comment listing eitehr the Company name, or Domain owner.
This may proove useful for future research.

Do you have any other useful research sites?

**Comment by duramato** [comment]
This has an api http://www.yougetsignal.com/tools/web-sites-on-web-server/
