### ISSUE TITLE
Alpine-installation might need to be a separate file?

### ISSUE THREAD

**Issue by Serkan-devel** [quidsup/notrack#64]
After some digging into the alpine-VM and tweaking the install.sh-file couldn't execute the file due to <code>bash</code> not existing. Instead there is <code>sh</code> available. Does it make a difference if sh is used? It can exec files like bash too. Could we change the already existing install file to use sh or should it be a separate file using sh?

**Comment by quidsup** [comment]
I'll have to look, because all the script files are using Bash

**Comment by Serkan-devel** [comment]
Btw. <code>sudo</code> isn't installed by default

**Comment by Serkan-devel** [comment]
### I'm active again
I guess there is no problem install the install.sh file over bash. No extra file needed. There might need to be instructions showing how to install it on alpine explicitly. 
<code>apk add bash</code>
