### ISSUE TITLE
Sites Blocked not counting

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#71]
I've always had this issue, i'm not sure if it's working for anyone else, but the home page where it says "Sites Blocked" will show 0, or a very low amount, and when i click on it. it shows only locally blocked connection

http://prntscr.com/c2vaor
http://prntscr.com/c2vaqw (Ignore port 81, i switched it back, its just keeping log of it)
But you can see i have stuff being blocked http://prntscr.com/c2vayp
Incase it matters here's my settings page http://prntscr.com/c2vb8g
http://prntscr.com/c2vbnc and http://prntscr.com/c2vbro (disconnect.net and malwaredomainlist.com wont stay checked) 

P.S. sorry for all the prntscr.com's

**Comment by quidsup** [comment]
I'll checkout the two block lists tomorrow, I changed all the variable names for the block lists. Config.php line 374,375,870,and 877 have the incorrect names.

As for sites blocked, it's reading the access log from lighttpd. You'll loose that functionality without lighttpd supplying the sinkhole page

**Comment by quidsup** [comment]
Should be resolved in 0.8.1 using the Time display view in blocked.php
