### ISSUE TITLE
Notrack blocking all .de domains even when whitelisted

### ISSUE THREAD

**Issue by Alexrocksdude** [quidsup/notrack#72]
No .de domains are working even with the domain blocklist disabled and "*.de" on the whitelist.

**Comment by quidsup** [comment]
Domains are handled differently in terms of whitelisting.
Have a look to see if .de is in /etc/notrack/domain-blacklist.txt
Or /etc/notrack/blacklist.txt

If it is delete the line and run sudo notrack -f

**Comment by Alexrocksdude** [comment]
No .de in either and its still being blocked after i ran "sudo notrack -f"

**Comment by quidsup** [comment]
Ok, perhaps its in a third party block list?
Can you paste the output of "notrack --test"

**Comment by quidsup** [comment]
Can you see .de in Sites blocked list?
/admin/config.php?v=sites&s=.de

**Comment by Alexrocksdude** [comment]
```
NoTrack Config Test

NoTrack version v0.7.15
Config file /etc/notrack/notrack.conf
Reading Config File
Internet Protocol Version 4 (IPv4)
Reading IPv4 Address from eth0
System IP Address: x.x.x.x

Block Lists Utilised:
NoTrack 1
TLD 0
Hexxium 1
QMalware 1
AdBlockManager 1
DisconnectMalvertising 1
EasyList 1
EasyPrivacy 1
FBAnnoyance 1
FBEnhanced 1
FBSocial 1
hpHosts 0
MalwareDomainList 0
MalwareDomains 1
PglYoyo 1
Secure Mecca 1
SomeoneWhoCares 1
Spam404 1
SwissRansom 1
SwissZeus 1
Winhelp2002 0
AR Easy 0
CHN Easy 0
DEU Easy 0
DNK Easy 0
RUS Easy 0
Custom
```

There are multiple (~200?) .de sites but some, such as google.de and fau.de are still being blocked even though they are not included in the list.

**Comment by quidsup** [comment]
I've traced the fault to the Secure Mecca block list

**Comment by quidsup** [comment]
Secure Mecca contains the line:
`127.0.0.1       www.de`

In processing block lists NoTrack drops preceding www.
It will literally interpret the line as blocking the entire .de domain

There is no way I can resolve this, I will have to remove Secure Mecca block list

**Comment by Alexrocksdude** [comment]
That's a shame, but nice to know I can go back to using local mirrors and ntp servers.
:)
