### ISSUE TITLE
Typo in a domain

### ISSUE THREAD

**Issue by p1r473** [quidsup/notrack#73]
One of the domains has a typo in it in the list:

kaloo.ga#Kalooga

Should have a space between it, as so:
kaloo.ga #Kalooga

It was breaking some stuff on my end. Sorry, I couldnt see an email to report it, so putting it here.

**Comment by quidsup** [comment]
I rarely check the couple of email addeesses I have published.
Raising the issue here was the quickest way for me to see it.

It was a quick fix and I've pushed the update
