### ISSUE TITLE
Missing Image on Login

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#74]
Seems to be a constant missing image, i've installed notrack on my NAS and a VM and it does this.

When i go to login on the top left there's a missing image icon.
http://prntscr.com/c4ogf9 Which i assume is a NoTrack logo.

EDIT: After copying image location and going to it, it seems it's blocking its own image :+1: 
http://192.168.0.100/admin/svg/ntrklogo2.svg shows http://prntscr.com/c4ohea (and this is using stock Lighttpd(automaticly installed with installer), and dnsmasq setup you showed in your tutorial)

**Comment by quidsup** [comment]
Thanks, I forget about testing that page.

I've fixed it, and will include it a bulk commit later on

**Comment by ShayBox** [comment]
Thanks :D
