### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by dodlaz** [quidsup/notrack#79]
Whitelist addresses will be blocked if the top level domain is blocked.

**Comment by quidsup** [comment]
Yes its a limitation of Dnsmasq that you can't allow a specific site and block its top level domain.
So far my only idea is to store the resolved IP in another .list file, e.g.:
`address/whitelistedsite.com/1.1.1.1`
`address/.com/192.168.1.2` (NoTrack)
but that could be prone to failure if the site regularly changes IP.

Ideally a secondary DNS server is required to ensure the correct IP is given

**Comment by quidsup** [comment]
Confirmed my theory works
With .cc domain blocked I was able to add site road.cc into a new .list file and browse to it.

It depends on having dnsutils installed (which it wasn't on Raspbian)

```
$ dig road.cc @8.8.8.8 +noall +answer | cut -f6 -d$'\t'

; <<>> DiG 9.10.3-P4-Ubuntu <<>> road.cc @8.8.8.8 +noall +answer
;; global options: +cmd
54.230.11.228
54.230.11.246
```
```
sudo nano /etc/dnsmasq.d/white.list 
address=/road.cc/54.230.11.228
address=/road.cc/54.230.11.246

sudo service dnsmasq restart
```

Testing the result
```
dig road.cc

; <<>> DiG 9.10.3-P4-Ubuntu <<>> road.cc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58272
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;road.cc.                       IN      A

;; ANSWER SECTION:
road.cc.                300     IN      A       54.230.11.228

;; Query time: 3 msec
```

Not exactly perfect, but enough to access the site successfully

**Comment by quidsup** [comment]
`server=/site.com/#`
Forces Dnsmasq to carry out proper DNS resolution.
However it only works in version 2.75 onwards.
(Raspbian Jessie comes with version 2.72)

**Comment by quidsup** [comment]
Latest commit allows users with dnsmasq 2.75 onwards to white list.
Still need to write fall back version with Dig

**Comment by quidsup** [comment]
Feature added
