### ISSUE TITLE
Incorrect current version

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#82]
After checking the update page, this shows up http://prntscr.com/c783yd and when i clicked force update, it worked. but it still shows the same thing, the message at the bottom and the version number didn't change. but if i click it again it just shows http://prntscr.com/c7855y 
Not a very urgent bug, as it does update. it just doesn't show it as changed version

**Comment by quidsup** [comment]
I'm holding formal release back until one final test is complete.
I want to make sure that notrack.sh does a list update after four days, but I kept messing around with it instead of leaving it alone
