### ISSUE TITLE
0.7.15/16 dashboard issue

### ISSUE THREAD

**Issue by kre2** [quidsup/notrack#96]
dashboard 0.7.15 only show default domains,white/blacklist no matter what other domains,white/blacklist is checked-box
dashboard  0.7.16 block is own dashboard get the 1 pixel image
tried fresh install on 2 different sd-card same result
redownload 0.7.15 and install on top of 0.7.16 seems to fix domains,white/blacklist checkbox issue

**Comment by quidsup** [comment]
Blocking the dashboard would indicate there are files missing.
Check the symlink in /var/www/html to see if it is pointing to the correct folder
`$ ls -l /var/www/html/`

e.g.
```
lrwxrwxrwx 1 root     root       26 Jan  7  2016 admin -> /home/quids/NoTrack/admin/
drwxrwxr-x 2 www-data www-data 4096 Jul 12 20:56 sink
```

Or it could be a permissions issue
`ls -l /etc/notrack/`

Maybe changing permissions to 775 or 777 will help.
`sudo chmod -R 775 /etc/notrack`

**Comment by kre2** [comment]
Hi Quidsup
I upgraded agian to 7.16 (no fresh install) and no problems with dashboard
$ ls -l /var/www/html/
total 8
lrwxrwxrwx 1 root     root       22 Aug 17 17:24 admin -> /home/pi/notrack/admin
-rwxrwxr-x 1 root     root     3373 Aug 17 14:37 index.lighttpd.html
drwxrwxr-x 2 www-data www-data 4096 Aug 17 17:24 sink

 $ ls -l /etc/notrack/
total 5616
-rw-r--r-- 1 root     root         191 Aug 17 16:48 blacklist.txt
-rw-r--r-- 1 root     root     4330664 Aug 22 13:14 blocking.csv
-rw-r--r-- 1 root     root          83 Aug 22 13:10 custom.csv
-rw-r--r-- 1 root     root      114253 Aug 22 13:12 disconnectmalvertising.csv
-rw-r--r-- 1 www-data www-data     344 Aug 19 17:48 domain-blacklist.txt
-rw-r--r-- 1 root     root         263 Aug 22 13:10 domain-quick.list
-rw-r--r-- 1 root     root          43 Aug 19 17:48 domain-whitelist.txt
-rw-r--r-- 1 root     root      119355 Aug 22 13:13 easylist.csv
-rw-r--r-- 1 root     root       91811 Aug 22 13:14 easyprivacy.csv
-rw-r--r-- 1 root     root        7131 Aug 22 13:14 fbannoyance.csv
-rw-r--r-- 1 root     root        1844 Aug 22 13:14 fbenhanced.csv
-rw-r--r-- 1 root     root        3295 Aug 22 13:11 hexxium.csv
-rw-r--r-- 1 root     root       29300 Aug 22 13:14 malwaredomainlist.csv
-rw-r--r-- 1 root     root      507979 Aug 22 13:12 malwaredomains.csv
-rw-r--r-- 1 root     root         698 Aug 22 12:56 notrack.conf
-rw-r--r-- 1 root     root      334587 Aug 22 13:11 notrack.csv
-rw-r--r-- 1 root     root         724 Aug 22 13:11 qmalware.csv
-rw-r--r-- 1 root     root      130174 Aug 22 13:13 spam404.csv
-rw-r--r-- 1 root     root        6703 Aug 22 13:13 swissransom.csv
-rw-r--r-- 1 root     root        6050 Aug 22 13:13 swisszeus.csv
-rw-r--r-- 1 root     root         984 Aug 22 13:10 tld.csv
-rw-r--r-- 1 root     root         155 Aug 19 19:37 whitelist.txt

I hope is look okay......i think so
and thanks for your support
cheers kresten DK
